#!/usr/bin/env python3
# jaccard-corpus.py
# Corpus de CONTEXT_LOCAL aprovados — usado para validar Jaccard de novas cidades.
# Regra: nova cidade precisa ter Jaccard < 0.20 contra TODOS os textos abaixo.
# Adicionar novo entry aqui após cada LP aprovada.

import re

def tokenize(text):
    text = re.sub(r'<[^>]+>', ' ', text)
    text = text.lower()
    return set(re.findall(r'[a-záàâãéêíóôõúüç]+', text))

def jaccard(a, b):
    sa, sb = tokenize(a), tokenize(b)
    return len(sa & sb) / len(sa | sb)

def check(candidate_text, candidate_name="Nova cidade"):
    results = []
    ok = True
    for name, text in CORPUS.items():
        j = jaccard(candidate_text, text)
        status = "OK" if j < 0.20 else "FALHOU"
        if j >= 0.20:
            ok = False
        results.append((name, j, status))
    print(f"\n=== Jaccard: {candidate_name} ===")
    for name, j, status in sorted(results, key=lambda x: -x[1]):
        print(f"  vs {name:<25} {j:.3f}  {status}")
    print(f"  Resultado geral: {'OK — pode publicar' if ok else 'FALHOU — reescrever'}")
    return ok

# ---------------------------------------------------------------------------
# CORPUS APROVADO
# ---------------------------------------------------------------------------

CORPUS = {}

CORPUS["Pará de Minas"] = """<p>Pará de Minas construiu sua economia sobre dois pilares complementares: a indústria de transformação e um comércio varejista que serve toda a região Oeste de Minas. O polo industrial concentra metalurgia, laticínios, indústria química e têxtil — setores que respondem por mais de 40% do PIB municipal. O comércio, por sua vez, atrai consumidores de dezenas de municípios vizinhos, tornando a cidade referência regional em serviços.</p>
<p>Para o empresário local, esse perfil gera desafios tributários específicos. Metalúrgicas acumulam créditos de IPI sobre insumos que raramente são aproveitados. Laticínios operam com substituição tributária de ICMS que, se mal gerida, resulta em pagamento duplo. Empresas de comércio varejista perdem competitividade quando o regime tributário não é calibrado para o seu faturamento real.</p>
<p>A AC Contabilidade nasceu em Pará de Minas em 1996 e cresceu junto com o tecido empresarial da cidade. Três décadas acompanhando comércio, serviços e indústrias locais traduzem-se em capacidade de identificar, com precisão, onde cada tipo de empresa paga tributo além do necessário — e como recuperar esse valor dentro da legalidade.</p>
<p>O escritório fica na Rua Major Fidélis, 244, no Centro de Pará de Minas. O atendimento pode ser presencial ou por videoconferência para empresas de outras cidades. Para novos clientes, o diagnóstico tributário gratuito é o ponto de partida.</p>"""

CORPUS["Sete Lagoas"] = """<p>Sete Lagoas construiu sua identidade econômica sobre o ferro. O Distrito Industrial, inaugurado em 1974, reuniu fundições, siderúrgicas e metalúrgicas que transformaram a cidade no maior polo siderúrgico do interior mineiro. Empresas como a Iveco, que fabrica veículos pesados no município, e grandes marcas do setor de alimentos como Ambev e Itambé instalaram operações que elevaram a cidade à 12ª maior economia de Minas Gerais.</p>
<p>Para o empresário sete-lagoano, esse perfil industrial gera um desafio tributário específico. Fundições e metalúrgicas acumulam créditos de ICMS e IPI sobre insumos e materiais intermediários que, na maior parte dos casos, nunca são aproveitados. Distribuidoras de alimentos operam com margens apertadas e perdem competitividade quando o regime tributário não é calibrado corretamente. A AC Contabilidade existe para fechar essa lacuna.</p>
<p>Atendemos Sete Lagoas desde 1996. Ao longo de três décadas, acompanhamos o crescimento do polo industrial, as mudanças no regime do ICMS em MG e a chegada de novos setores, como o farmacêutico. Esse histórico permite identificar, com precisão, onde cada tipo de empresa da região acumula tributo pago a mais, e como recuperar esse valor dentro da legalidade.</p>
<p>O escritório fica a menos de uma hora de Sete Lagoas pela BR-040, a 72 km de BH. O atendimento pode ser presencial ou por videoconferência. Para empresas do Distrito Industrial, do eixo comercial do Eldorado ou dos bairros do Centro e São João, o diagnóstico tributário gratuito é o ponto de partida.</p>"""

CORPUS["Montes Claros"] = """<p>Montes Claros chegou ao século XXI como o centro econômico do Norte de Minas — 5ª maior cidade do estado, com PIB de R$ 10,8 bilhões e uma estrutura produtiva que poucos municípios do interior brasileiro conseguem igualar. Nestlé, Novo Nordisk, Eurofarma, Coteminas e MSD transformaram o município na capital nacional de medicamentos e no maior produtor de leite condensado do mundo. Esse perfil atrai investimento, gera volume fiscal e exige contabilidade à altura da complexidade.</p>
<p>Farmacêuticas brasileiras e multinacionais têm regimes de PIS/COFINS com alíquotas não cumulativas que geram direitos a ressarcimento raramente explorados pelos escritórios contábeis convencionais. Fabricantes de laticínios e alimentos processados convivem com ICMS-ST calculado sobre pautas fiscais que mudam por decreto e que, quando mal monitoradas, resultam em recolhimento acima do valor real devido. A AC Contabilidade foi construída para tratar essas variáveis, não para ignorá-las.</p>
<p>A AC Contabilidade está no Norte de Minas desde 1996. Nesse tempo, vimos a ZFM farmacêutica ganhar corpo, o ICMS-ST ser reformulado e o setor de serviços superar a indústria em participação no PIB local. Acumular esse tipo de vivência setorial significa reconhecer padrões que escritórios recentes simplesmente não enxergam.</p>
<p>O formato de reunião se adapta à rotina do cliente. Quem está em Montes Claros pode optar pela chamada de vídeo, eliminando horas de deslocamento. Quem prefere o encontro presencial tem o escritório de Pará de Minas como referência. O ponto de entrada é sempre o mesmo: um levantamento completo e gratuito que mapeia tributação vigente, créditos não utilizados nos últimos cinco anos e situação patrimonial do sócio.</p>"""


CORPUS["Uberaba"] = """<p>Uberaba é a capital genética do mundo: o município exporta embriões e sêmen de zebuínos para mais de 80 países, centraliza os principais leilões da raça Nelore e abriga a maior feira de gado bovino das Américas, a ExpoZebu. Esse eixo agropecuário sustenta um ecossistema de empresas rurais, veterinárias, laboratórios de reprodução e agroindústrias cujas obrigações fiscais vão muito além do ITR e do Funrural típicos do produtor rural.</p>
<p>Pecuaristas com operações de exportação de material genético precisam controlar o tratamento cambial da receita em moeda estrangeira, a isenção de ICMS nas saídas interestaduais para exportação e o crédito de PIS/COFINS sobre insumos veterinários. Frigoríficos e laticínios do entorno operam com crédito presumido de PIS/COFINS da agroindústria, cuja apuração incorreta compromete dezenas de pontos de margem. Distribuidoras atacadistas que servem o varejo regional enfrentam o ICMS-ST sobre alimentos com pautas fiscais que mudam por portaria estadual sem aviso prévio.</p>
<p>Trinta anos de presença no interior mineiro geraram uma base metodológica construída sobre casos reais, não sobre teoria. A AC Contabilidade acompanhou as mudanças no regime do Simples Nacional, a reforma do ICMS em MG e as sucessivas alterações nas listas de NCMs sujeitos à substituição tributária. Esse histórico permite antecipar impactos regulatórios antes que eles se tornem custos para o cliente.</p>
<p>O levantamento tributário inicial é gratuito e ocorre por reunião virtual, sem deslocamento. O escopo cobre regime atual, créditos escriturados nos últimos sessenta meses e riscos fiscais identificados na escrituração vigente.</p>"""

CORPUS["Uberlândia"] = """<p>Uberlândia funciona como o nó central de redistribuição logística do Brasil Central: as rodovias BR-050, BR-365 e BR-452 convergem no município, posicionando a cidade como plataforma de abastecimento para o agronegócio do Cerrado e para o varejo de todo o eixo Sudeste-Centro-Oeste. Com PIB acima de R$ 30 bilhões e centenas de distribuidoras, transportadoras e fabricantes de médio porte, a base empresarial local gera um volume de obrigações periódicas que excede a capacidade operacional de escritórios de estrutura convencional.</p>
<p>Distribuidoras multiestaduais acumulam ativo de ICMS nas entradas que, por deficiência na apuração mensal, permanece represado sem gerar benefício de caixa. Frotas próprias de transportadoras precisam contabilizar o diferencial de alíquota de ICMS na compra de veículos pesados e o encargo previdenciário sobre remuneração de motoristas autônomos — dois pontos tratados pela legislação de forma distinta do regime CLT. Atacadistas próximos do teto do Supersimples postergam a transição de modalidade por falta de simulação comparativa, e cada trimestre de inércia pode ultrapassar o custo de uma análise de reenquadramento.</p>
<p>Definir o ponto exato de menor pressão fiscal para cada estrutura exige domínio setorial acumulado ao longo de décadas, não apenas familiaridade com a legislação vigente. A vivência em assessoria a operações de distribuição, logística e comércio atacadista do interior de MG é o que fundamenta diagnósticos precisos.</p>
<p>Para novos clientes de Uberlândia, o ponto de partida é um levantamento fiscal sem custo, conduzido por videoconferência. O trabalho abrange modalidade tributária atual, crédito acumulado nos cinco anos anteriores e os pontos de risco identificados na escrituração da empresa.</p>"""

CORPUS["Poços de Caldas"] = """<p>Poços de Caldas reúne, no mesmo perímetro urbano, um parque industrial com cerâmica técnica de alta temperatura, alumínio refratário e laboratórios de pesquisa de multinacionais, e um complexo hoteleiro que sustenta fluxo turístico ao longo de todos os doze meses. A Novelis instalou na cidade um centro técnico que atende operações sul-americanas, e outras corporações globais seguiram o mesmo caminho atraídas pela altitude, pela infraestrutura universitária e pela qualificação da mão de obra local.</p>
<p>Cerâmicas técnicas e fundições de alumínio classificam seus produtos por NCM e essa codificação determina diretamente a alíquota de IPI aplicável. Quando a Tabela TIPI é atualizada por decreto e a empresa não revisa a classificação vigente, o tributo recolhido diverge do correto por anos, gerando ora passivo ora crédito não percebido. Estabelecimentos hoteleiros calculam ISS sobre hospedagem pela tabela municipal de Poços e precisam reter IRRF em notas emitidas para tomadores corporativos, pena de responsabilização tributária solidária na fiscalização. Desenvolvedoras de software do polo tecnológico local que atingem o limite do Supersimples precisam formalizar a opção pelo Lucro Presumido até o último dia útil de janeiro, prazo que a maioria descobre depois que a irretratabilidade já ocorreu.</p>
<p>Três décadas de acompanhamento a empresas do Sul de Minas construíram uma base de casos reais que cobre cerâmica, hotelaria, tecnologia e manufatura. Esse repositório de situações concretas é o que diferencia uma análise precisa de uma orientação genérica.</p>
<p>Novos clientes de Poços de Caldas começam pelo mapeamento fiscal gratuito, conduzido por conexão digital. O diagnóstico abrange modalidade tributária atual, créditos represados dos últimos sessenta meses e vulnerabilidades nas obrigações periódicas da empresa.</p>"""

CORPUS["Betim"] = """<p>Betim abriga a maior fábrica da Stellantis na América Latina e o Polo Petroquímico de Minas, dois vetores que transformaram a cidade no segundo maior PIB industrial do estado. A cadeia de fornecedores automotivos ao redor da planta — autopeças, sistemas, montagens e logística — gera centenas de empresas com obrigações fiscais de alta complexidade e fluxo de notas fiscais de entrada e saída que exige controle permanente.</p>
<p>Fornecedores da indústria automotiva operam com drawback, crédito presumido de IPI e regimes especiais de ICMS que poucas assessorias contábeis dominam na prática. Empresas do polo petroquímico precisam acompanhar as variações de NCM e de pauta fiscal do ICMS-ST em matérias-primas que mudam de classificação por ato normativo. Quando esses controles falham, o crédito acumula e o caixa sangra sem que a gestão identifique a causa.</p>
<p>A AC Contabilidade acumulou três décadas de vivência com os regimes tributários específicos da indústria mineira. Essa bagagem se traduz em capacidade de mapear, em auditoria retroativa de cinco anos, os créditos não aproveitados e quantificar o retorno concreto antes de formalizar qualquer proposta.</p>
<p>O formato de atendimento se adapta à rotina industrial: videoconferência em qualquer horário ou visita presencial ao escritório de Pará de Minas. Para novos clientes em Betim, a avaliação tributária inicial não tem custo e não exige compromisso de contratação.</p>"""

CORPUS["Curitiba"] = """<p>Curitiba consolidou sua posição como o principal polo de tecnologia e inovação do Sul do Brasil. A capital paranaense reúne empresas de software, segurança da informação, automação industrial e serviços especializados que operam em modelos de negócio híbridos, com receita de produto e de serviço misturadas numa mesma pessoa jurídica. Esse perfil cria desafios tributários que escritórios contábeis generalistas raramente conseguem resolver com precisão.</p>
<p>Empresas de tecnologia que faturam acima de R$ 78 milhões no Simples Nacional precisam migrar de regime, mas a transição exige planejamento: créditos de PIS/COFINS acumulados na fase cumulativa podem ser aproveitados na não cumulativa e, se não forem mapeados no momento certo, prescrevem em cinco anos. Prestadores de serviços com clientes em vários estados precisam gerenciar o ISS da competência tributária municipal e o IRRF retido na fonte, que nem sempre é compensado corretamente.</p>
<p>Trinta anos de prática com empresas do interior mineiro construíram um modelo de trabalho que funciona inteiramente por meios digitais, sem perda de profundidade analítica. Acesso remoto seguro a sistemas contábeis, reuniões por videoconferência e entrega de relatórios em tempo real permitem atender empresas de Curitiba com a mesma qualidade oferecida a clientes vizinhos ao escritório.</p>
<p>A primeira conversa não tem custo: um diagnóstico tributário de 30 minutos que revela o regime mais vantajoso, os créditos que podem ser recuperados dentro do prazo legal e os riscos que precisam ser corrigidos antes que se tornem autuações. Sem compromisso, sem burocracia.</p>"""

CORPUS["Sorocaba"] = """<p>Sorocaba estruturou seu parque produtivo ao longo da ferrovia que interliga Santos a Bauru, e hoje esse legado industrial se expressa em plantas de equipamentos elétricos de média e alta tensão, tecelagens técnicas, linhas de produção farmacêutica e fabricantes de autopeças que tornam a cidade a quarta maior economia do interior paulista. A diversidade de setores num mesmo perímetro urbano significa que obrigações fiscais com lógicas completamente distintas coexistem a poucos quarteirões de distância.</p>
<p>Fabricantes de equipamentos elétricos de alta tensão precisam classificar cada produto por TIPI para determinar se a saída é tributada, imune ou sujeita a alíquota reduzida de IPI: uma classificação incorreta gera estorno de crédito ou multa proporcional conforme o sentido do erro. Tecelagens técnicas que exportam tecidos especializados para o mercado têxtil global calculam o benefício de suspensão de tributos na aquisição de fios, mas o controle do saldo exportado por partida é o que determina se a suspensão se converte em isenção definitiva. Indústrias farmacêuticas instaladas no Distrito Industrial de Além Ponte operam com regimes de PIS e COFINS por alíquota diferenciada de produto, e qualquer divergência entre o regime declarado e o efetivamente praticado gera inconsistência que a Receita Federal detecta na cruzagem entre a EFD-Contribuições e a NFe.</p>
<p>A prática de três décadas com empresas da indústria de transformação formou uma base de conhecimento setorial que permite detectar, com precisão, onde cada tipo de operação acumula carga tributária além do que a legislação exige.</p>
<p>Novos clientes de Sorocaba passam por uma triagem tributária gratuita conduzida à distância. A avaliação cobre o regime de tributação atual, o aproveitamento de crédito dos cinco exercícios anteriores e os pontos de atenção identificados nas declarações periódicas da empresa.</p>"""

CORPUS["Guarulhos"] = """<p>Guarulhos concentra um volume fiscal proporcional ao Aeroporto Internacional de Cumbica, segundo maior do Brasil em movimentação de cargas. Operadores logísticos, tradings, despachantes aduaneiros e distribuidoras que movimentam mercadorias de todos os continentes têm sede ou filial no município, atraídas pela malha rodoviária que liga Anhanguera, Dutra e Presidente Dutra num único nó de distribuição para toda a Grande SP.</p>
<p>Importadoras precisam classificar corretamente o NCM de cada mercadoria para definir a alíquota de IPI e evitar autuações da Receita Federal na entrada. Tradings que revendem mercadoria importada para varejistas paulistas enfrentam ICMS-ST com pauta fiscal específica e substituição tributária de ponta, cujo cálculo incorreto gera passivo que só aparece na fiscalização estadual. Operadores logísticos com frota própria precisam controlar o ICMS diferencial de alíquota na aquisição de veículos e o INSS sobre terceiros contratados.</p>
<p>Três décadas de assessoria a empresas com cadeias tributárias complexas consolidaram uma metodologia que parte do mapeamento das entradas e saídas antes de qualquer recomendação. Esse diagnóstico de base revela exatamente onde o tributo está sendo pago além do necessário.</p>
<p>O levantamento inicial é gratuito e ocorre por chamada de vídeo. O escopo cobre regime atual, créditos acumulados nos últimos sessenta meses e riscos identificados nas obrigações acessórias vigentes.</p>"""

CORPUS["Manaus"] = """<p>Manaus opera sob normas tributárias sem equivalente no restante do Brasil. A Zona Franca criada pelo Decreto-Lei 288/1967 concede desoneração de Imposto de Importação e IPI para componentes destinados à fabricação no Polo Industrial, além de redução nas remessas interestaduais e alíquota diferenciada de contribuições sociais em determinadas cadeias de valor, consolidando a cidade como a maior produtora nacional de eletroeletrônicos de consumo, motocicletas e televisores, com mais de 500 plantas habilitadas.</p>
<p>Cada empresa do Polo precisa comprovar o cumprimento do Processo Produtivo Básico para cada linha de produto e manter escrituração segregada por habilitação para sustentar os benefícios perante a Suframa e a Receita Federal. O diferencial de ICMS concedido pelo Amazonas nas saídas para o restante do país é calculado por portaria estadual com tabelas por categoria, e a aplicação incorreta gera estorno em cascata que transforma o incentivo em passivo de difícil reversão. Distribuidoras e prestadoras de serviços que atuam fora do polo de manufatura não usufruem dos mesmos incentivos dos fabricantes, mas podem enquadrar determinadas operações em regimes favorecidos do ICMS-AM se a atividade for tipificada corretamente na classificação estadual.</p>
<p>Três décadas de assessoria a estruturas fiscais de elevada complexidade consolidaram uma metodologia de mapeamento que parte das condicionantes específicas de cada habilitação para localizar onde o incentivo está sendo sub-aproveitado ou onde há risco de glosa retroativa.</p>
<p>Para novos clientes de Manaus, o diagnóstico fiscal inicial não tem custo e ocorre por transmissão remota. O levantamento abrange o enquadramento na ZFM, o aproveitamento de benefícios no quinquênio anterior e as inconsistências nos arquivos enviados à Suframa e ao Fisco Federal.</p>"""

CORPUS["Osasco"] = """<p>Osasco consolidou-se como o maior polo de serviços financeiros do Brasil fora de São Paulo capital: bancos de médio porte, cooperativas de crédito, seguradoras, fintechs e administradoras de consórcio instalaram sedes e centros de operações ao longo da Avenida dos Autonomistas, atraídos pela proximidade com a Marginal Pinheiros e pela infraestrutura de telecomunicações que permite processar alto volume de transações com latência mínima.</p>
<p>Bancos e cooperativas de crédito escrituram o IOF sobre operações de empréstimo e financiamento com alíquotas que variam por prazo e modalidade, e qualquer inconsistência entre o IOF declarado e o efetivamente recolhido gera auto de infração de difícil contestação administrativa. Seguradoras precisam controlar a tributação sobre prêmios e sinistros com tratamento diferenciado de IRPJ e CSLL, além do IOF específico sobre apólices, cujo cálculo correto depende da classificação precisa de cada tipo de cobertura contratada. Fintechs que crescem além do teto do Simples Nacional precisam decidir entre Lucro Presumido e Lucro Real considerando o impacto específico sobre PIS e COFINS em operações de crédito e intermediação financeira, tributos com tratamento distinto do regime padrão de prestação de serviços.</p>
<p>A vivência de três décadas com empresas do setor financeiro e de serviços especializados consolidou uma base metodológica para detectar onde a tributação está sendo apurada além do exigido pela legislação vigente.</p>
<p>Empresas de Osasco que queiram iniciar uma revisão tributária recebem uma avaliação gratuita por videoconferência. O diagnóstico abrange o regime de tributação atual, o histórico de aproveitamento de crédito nos cinco exercícios anteriores e os pontos de vulnerabilidade fiscal identificados na escrituração contábil.</p>"""

CORPUS["Caxias do Sul"] = """<p>Caxias do Sul é o maior polo metal-mecânico do Sul do Brasil, herança da imigração italiana que transformou a Serra Gaúcha em berço da indústria de precisão nacional. Fabricantes de implementos rodoviários, peças automotivas, equipamentos agrícolas e sistemas de transmissão exportam para mais de 80 países a partir do município. A cadeia vinícola, segundo eixo econômico da cidade, acrescenta uma camada de obrigações fiscais raramente encontrada em outros polos industriais gaúchos.</p>
<p>Indústrias metal-mecânicas com operações de exportação utilizam o drawback para suspender tributos na entrada de insumos importados e crédito de IPI sobre componentes adquiridos no mercado interno. O regime de ICMS do RS concede benefícios específicos para manufaturados destinados à exportação, mas exige escrituração segregada e cumprimento de condicionantes que variam por portaria estadual. Vinícolas e produtores de espumantes convivem com ICMS-ST sobre bebidas calculado com base em pautas fiscais por categoria, e o acompanhamento mensal dessas tabelas é o que separa o recolhimento correto do passivo silencioso.</p>
<p>Três décadas de prática tributária com indústrias do interior brasileiro consolidaram uma metodologia de auditoria retroativa que quantifica o saldo credor represado, estima o valor recuperável e apresenta o resultado antes de qualquer proposta de honorários.</p>
<p>O atendimento começa por chamada de vídeo, sem necessidade de deslocamento. O levantamento tributário inicial é gratuito: cobre enquadramento atual, créditos acumulados nos últimos sessenta meses e riscos mapeados na escrituração vigente.</p>"""

CORPUS["Fortaleza"] = """<p>Fortaleza lidera a produção calçadista do Nordeste brasileiro e abriga um dos maiores complexos têxteis do país, com fabricantes de rendas, bordados industriais e confecção de moda que abastecem varejistas de quatro continentes. A capital cearense não é só polo de manufatura: o turismo litorâneo sustenta uma rede hoteleira e de gastronomia que opera durante o ano inteiro, e o Maracanaú Industrial, distrito contíguo, concentra farmacêuticas e distribuidoras que ampliam a base fiscal do município.</p>
<p>Fábricas de calçados do Ceará operam sob regime de tributação concentrada, em que as contribuições sobre a receita são recolhidas pelo fabricante ou importador de matéria-prima a uma alíquota específica por código de produto, eliminando a incidência nas etapas seguintes. Quando a cadeia de fornecimento envolve partes importadas de países com acordo de não-dupla-tributação, a apuração do imposto de importação exige classificação correta na Tabela TIPI e validação das condicionantes do regime especial, dois pontos que a maioria dos escritórios convencionais terceiriza sem domínio real. Hotéis e pousadas de Fortaleza calculam a contribuição ao Fundo Municipal de Turismo sobre a receita de hospedagem, parcela que integra a base de cálculo do ISS mas raramente está segregada na escrituração padrão, gerando inconsistências visíveis em cruzamentos eletrônicos da Secretaria Municipal de Finanças.</p>
<p>A base metodológica construída em três décadas de assessoria a fabricantes e prestadores de serviços de diferentes perfis permite mapear, com exatidão, onde cada operação acumula tributação acima do que a legislação determina.</p>
<p>Para empresas de Fortaleza, a análise de viabilidade tributária não tem custo. O trabalho acontece por formato digital, abrange o enquadramento atual da empresa, o aproveitamento de crédito no período de prescrição de cinco anos e as inconsistências identificadas nos arquivos de escrituração periódica.</p>"""

CORPUS["Goiânia"] = """<p>Goiânia se posiciona como o maior centro de saúde privada do Centro-Oeste brasileiro e a principal praça comercial do agronegócio goiano. Hospitais oncológicos de referência nacional, clínicas de reprodução assistida, hemodinâmica e ortopedia de alta complexidade operam ao lado de tradings de soja, milho e algodão que movimentam contratos bilionários por safra, criando uma base fiscal de duas velocidades dentro do mesmo município.</p>
<p>Clínicas e hospitais de médio porte que ultrapassaram o teto do regime unificado precisam calcular a carga tributária comparativa entre regimes antes de tomar a decisão anual, que é irretratável: a proporção entre folha de especialistas e receita total define qual modalidade gera menor pressão fiscal, e essa equação muda conforme o mix de procedimentos. Tradings agropecuárias escrituram a contribuição previdenciária sobre a receita bruta de operações de exportação e precisam acompanhar as mudanças na legislação de ICMS/GO sobre transferências interestaduais de commodities, cujo diferimento varia por decreto do Conselho de Política Fazendária. Distribuidoras de defensivos e fertilizantes operam com ICMS com alíquota reduzida ou diferida para insumos destinados à produção agropecuária, benefício condicionado à destinação efetiva do produto e à emissão correta de documentos fiscais por operação.</p>
<p>A prática de três décadas com empresas de perfil fiscal diversificado consolidou uma metodologia de diagnóstico que parte dos dados reais de cada operação antes de sugerir qualquer alteração de estrutura ou regime.</p>
<p>Novos clientes de Goiânia recebem uma avaliação tributária sem custo, conduzida por conexão digital. O escopo abrange o regime de tributação atual, o período prescricional de cinco anos para aproveitamento retroativo de crédito e os pontos de risco detectados na escrituração periódica da empresa.</p>"""

CORPUS["João Pessoa"] = """<p>João Pessoa detém o litoral mais próximo da Europa entre todas as capitais brasileiras, e esse diferencial geográfico moldou uma economia baseada em turismo de alto padrão, educação superior e serviços de saúde que atendem moradores do interior paraibano a centenas de quilômetros de distância. Hotéis de bandeira internacional na orla de Tambaú, faculdades privadas no eixo da Avenida Epitácio Pessoa e hospitais especializados no Bairro dos Bancários formam um triângulo econômico com obrigações fiscais distintas por setor.</p>
<p>Estabelecimentos hoteleiros de João Pessoa calculam ISS sobre receita de hospedagem, café da manhã e serviços complementares separadamente, pois o município tributa cada atividade por alíquota própria estabelecida na lei complementar municipal, e a consolidação incorreta dos itens gera recolhimento a maior ou a menor detectável em cruzamento eletrônico com a nota fiscal de serviço. Faculdades e centros universitários privados que enquadram parte das receitas como imunes ou isentas de contribuições sociais precisam segregar com rigor os valores sujeitos ao PIS e ao COFINS das receitas protegidas, pois a ausência dessa segregação na EFD elimina o benefício por completo. Hospitais e clínicas que cobram procedimentos de pacientes de planos de saúde interligam ISS sobre a atividade médica, IRPJ sobre o resultado e retenção de IRRF sobre pagamentos a médicos autônomos, três obrigações que se cruzam em cada nota emitida.</p>
<p>A base acumulada em três décadas de assessoria a prestadores de serviços de diferentes portes permite identificar, com precisão cirúrgica, os pontos onde cada estrutura acumula carga tributária além do necessário.</p>
<p>A revisão tributária para novos clientes de João Pessoa é gratuita e ocorre por chamada digital. O trabalho cobre o regime fiscal atual da empresa, o aproveitamento dos créditos do período prescricional de cinco anos e as inconsistências identificadas nos documentos de apuração periódica.</p>"""

CORPUS["Ribeirão Preto"] = """<p>Ribeirão Preto centraliza a economia do agronegócio paulista: capital nacional do sucroalcooleiro, a cidade abriga usinas, destilarias e fornecedoras da cadeia canavieira que movimentam bilhões de reais por safra. Ao lado desse eixo produtivo, consolidou-se um complexo hospitalar e de biotecnologia referenciado em toda a América Latina, com hospitais universitários, centros de pesquisa clínica e clínicas oncológicas que atraem pacientes de dezenas de estados brasileiros.</p>
<p>Usinas sucroalcooleiras operam com crédito presumido de PIS/COFINS sobre a receita de etanol hidratado, ICMS com benefícios estaduais específicos para biocombustíveis concedidos pelo Estado de SP e Funrural sobre a produção rural integrada com fornecedores de cana. Hospitais e clínicas oncológicas de médio porte que ultrapassaram o teto do Supersimples precisam avaliar se o Lucro Presumido ou o Lucro Real gera menor carga, considerando a dedutibilidade de despesas médicas previstas na Lei 9.249 e o peso da folha de pagamento de especialistas no cálculo da CSLL. Distribuidoras de insumos agrícolas que transitam entre regimes acumulam crédito de ICMS nas entradas que, quando não escriturado mensalmente, vira ativo tributário represado sem gerar benefício de caixa.</p>
<p>A auditoria retroativa que aplicamos parte da escrituração existente para mapear o saldo credor acumulado em cada setor, quantifica o valor recuperável e apresenta o resultado antes de qualquer proposta de honorários.</p>
<p>O levantamento tributário de entrada é gratuito e ocorre por reunião virtual. O escopo abrange regime vigente, créditos acumulados nos últimos sessenta meses e riscos identificados na escrituração atual.</p>"""

CORPUS["Salvador"] = """<p>Salvador combina dois vetores produtivos de peso nacional: o Complexo Petroquímico de Camaçari, com mais de 90 unidades integradas por dutos, utilidades e vapor compartilhados, e o porto de Aratu, principal corredor de exportação da Bahia para granéis sólidos e fertilizantes. A cadeia de fornecedores que orbita essas duas âncoras gera um volume de obrigações acessórias que extrapola o que escritórios de estrutura genérica conseguem processar com rigor técnico.</p>
<p>Fornecedoras de insumos ao polo de Camaçari emitem notas com CFOPs específicos para transferência de produto entre estabelecimentos do mesmo grupo econômico, situação que a Sefaz baiana trata de modo distinto da venda interestadual comum: o uso do CFOP errado gera glosa de crédito de ICMS que só se revela na auditoria eletrônica, depois que o prazo para retificação já venceu. Construtoras pesadas que executam obras de ampliação nas plantas petroquímicas precisam segregar o ISS sobre mão de obra e o ICMS sobre materiais aplicados na obra, pois Salvador tributa cada componente por alíquota própria com notas de serviço e de mercadoria emitidas em separado. Prestadoras de manutenção industrial com contratos de longo prazo sujeitam cada fatura a retenção simultânea de CSLL, PIS, COFINS e IRRF quando o contratante é pessoa jurídica optante pelo Lucro Real, o que transforma o fluxo de caixa mensal numa variável dependente da configuração correta do contrato.</p>
<p>Três décadas de acompanhamento a estruturas com alta densidade de obrigações periódicas consolidaram uma metodologia para mapear passivos silenciosos antes que se transformem em autuação.</p>
<p>Para novos clientes de Salvador, a avaliação tributária inicial não tem custo e ocorre por videoconferência. O levantamento cobre o regime de tributação vigente, a revisão dos créditos acumulados no quinquênio e os pontos de fragilidade identificados nos arquivos de escrituração da empresa.</p>"""

CORPUS["Blumenau"] = """<p>Blumenau divide o espaço urbano entre o maior parque têxtil da Região Sul e um polo tecnológico com empresas de software, automação industrial e cibersegurança que faturaram mais de R$ 3 bilhões em 2023. A convivência entre teares jacquard e servidores de computação em nuvem não é apenas curiosidade histórica: ela cria obrigações fiscais com lógicas completamente distintas que convivem no mesmo perfil de contribuinte e exigem tratamento separado por atividade.</p>
<p>Fábricas de confecção do Vale do Itajaí que adotam o regime cumulativo de PIS e COFINS pagam alíquotas menores sobre a receita, mas abrem mão do crédito sobre insumos. Quando o volume de compras de tecido e aviamentos é alto em relação ao faturamento, o regime não cumulativo pode ser mais vantajoso, mas essa análise precisa ser feita com os números reais da empresa, não com estimativas setoriais. Marcas de moda blumenauenses que licenciam estampas e coleções para confeccionistas de outros estados precisam classificar o pagamento como royalty sujeito a IRPJ e CIDE ou como prestação de serviço sujeita a ISS, escolha que impacta diretamente a alíquota efetiva e a forma de retenção na fonte. Empresas de software com contratos de licença recorrente para clientes em municípios de outros estados enfrentam a controvérsia da LC 157/2016 sobre ISS: pagar no destino ou na origem é uma questão que cada prefeitura ainda interpreta à sua forma, gerando risco de bitributação ou de autuação por não retenção.</p>
<p>Três décadas de prática com indústrias de transformação e prestadores de serviços consolidaram uma metodologia para mapear o excedente tributário por atividade antes de propor qualquer ajuste de enquadramento.</p>
<p>Novos clientes de Blumenau recebem uma avaliação fiscal gratuita por videoconferência. O diagnóstico abrange o regime de tributação em vigor, os direitos creditórios dos últimos cinco exercícios e os pontos de inconsistência identificados na escrituração da empresa.</p>"""

CORPUS["Feira de Santana"] = """<p>Feira de Santana funciona como o principal nó de redistribuição comercial do Nordeste baiano: sua posição geográfica no cruzamento das rodovias BR-116 e BR-324 faz da cidade o ponto de passagem obrigatório para cargas que chegam de São Paulo, de Minas Gerais e dos portos do Sul antes de abastecer o semiárido e o litoral norte da Bahia. O Centro Industrial Subaé acrescenta a esse perfil fabricantes de calçados, artigos de couro e alimentos processados que vendem para mercados distantes com tributação estadual específica da Bahia.</p>
<p>Atacadistas redistribuidores de Feira de Santana que emitem notas fiscais de transferência para filiais em outros estados precisam usar os CFOPs corretos para cada tipo de movimentação: transferência entre estabelecimentos do mesmo contribuinte tem tratamento fiscal diferente de venda interestadual, e a confusão entre os dois gera apuração incorreta do ICMS que o auditor fiscal da Sefaz-BA localiza com precisão no cruzamento das GIAs. Fabricantes de artigos de couro e calçados que vendem para atacadistas do Sul e Sudeste precisam aplicar a alíquota interestadual correta por destino e calcular o DIFAL quando o comprador é consumidor final não contribuinte, dois pontos que a legislação estadual baiana trata em portarias distintas com tabelas atualizadas por período de competência. Distribuidoras de alimentos que transitam entre o Simples Nacional e o Lucro Presumido precisam avaliar o impacto da mudança no regime de substituição tributária da Bahia antes de efetuar a opção fiscal do ano seguinte.</p>
<p>A base acumulada em três décadas de assessoria a empresas comerciais e industriais permite mapear com precisão o tributo pago além do necessário e estimar o retorno antes de qualquer engajamento.</p>
<p>Para novos clientes de Feira de Santana, a primeira análise tributária é gratuita e ocorre por transmissão digital. O escopo cobre o enquadramento fiscal vigente, a revisão dos cinco últimos exercícios e os riscos de autuação identificados nos documentos de apuração periódica.</p>"""

CORPUS["Piracicaba"] = """<p>Piracicaba ocupa uma posição singular no interior paulista: a ESALQ da USP instalada às margens do rio desde 1901 tornou a cidade o principal centro de pesquisa em melhoramento genético de cana-de-açúcar do mundo, e esse legado científico sustenta hoje uma constelação de usinas, destilarias, fornecedores de cana e startups de bioenergia que operam com modelos de receita distintos dos setores industriais convencionais. A metalurgia agrícola voltada para colheitadeiras, prensas de bagaço e sistemas de bombeamento complementa esse perfil com uma base manufatureira de médio porte.</p>
<p>Usinas sucroalcooleiras do entorno de Piracicaba que vendem etanol hidratado para distribuidoras de combustível escrituram o crédito presumido de PIS e COFINS por tonelada de cana processada, mecanismo regulado por instrução normativa com tabela de valores atualizada anualmente pela Receita Federal: a aplicação do coeficiente do ano anterior gera apuração incorreta que se acumula silenciosamente ao longo do exercício. Cooperativas de fornecedores rurais que entregam cana a mais de uma usina dentro do mesmo período de safra precisam emitir nota de produtor para cada destinatário separado e controlar o Funrural por operação, pois o INSS rural incide sobre o valor bruto recebido em cada entrega sem compensação cruzada entre usinas. Fornecedores de peças e subconjuntos para colheitadeiras que atendem montadoras de São Paulo e Minas Gerais emitem nota com alíquota interestadual de ICMS e precisam acompanhar o DIFAL cobrado pelo estado do destinatário para não ser surpreendido com auto de infração estadual.</p>
<p>Três décadas de acompanhamento ao setor sucroalcooleiro e à metalurgia agrícola sedimentaram uma metodologia para mapear o excedente tributário com base nos registros reais da empresa.</p>
<p>Para novos clientes de Piracicaba, a triagem fiscal inicial não tem custo e ocorre por transmissão digital. O levantamento abrange o enquadramento vigente, a revisão dos créditos do quinquênio e as falhas de apuração identificadas nos arquivos periódicos da empresa.</p>"""

CORPUS["Recife"] = """<p>Recife reúne dois vetores econômicos de escala nacional que raramente coexistem numa mesma capital: o Porto Digital, ecossistema com mais de 300 empresas de software, games e serviços digitais no bairro histórico do Recife Antigo, e o Complexo Portuário de SUAPE, em Ipojuca, segundo maior porto do Nordeste e sede de operadores logísticos, refinaria e indústrias navais que movimentam bilhões em comércio exterior.</p>
<p>Empresas beneficiárias do Fundo de Incentivo à Cultura do Recife precisam cumprir condicionantes de geração de emprego e investimento para manter a isenção de ISS municipal: qualquer descumprimento gera estorno retroativo que transforma o benefício em passivo fiscal de difícil contestação. Operadores logísticos de SUAPE escrituram o ICMS sobre transferências de mercadorias em trânsito interestadual, o PIS e o COFINS sobre serviços de armazenagem em regime não cumulativo e a retenção de IRRF em contratos com tomadores pessoa jurídica, exigindo controle simultâneo de três esferas tributárias por operação. Desenvolvedoras de software sediadas no Porto Digital com contratos de licenciamento para clientes em outros estados precisam calcular o ISS conforme a legislação do município do tomador do serviço, não do prestador, o que exige conhecer a lista de serviços municipal de cada cidade onde o cliente está domiciliado.</p>
<p>Trinta anos de assessoria a empresas de diferentes portes e setores formaram uma base metodológica para mapear passivos ocultos e direitos creditórios com precisão antes de propor qualquer ajuste de enquadramento.</p>
<p>A consulta tributária inicial para novos clientes de Recife não tem custo e ocorre por transmissão digital. O diagnóstico cobre o regime de tributação em vigor, a auditoria dos últimos cinco exercícios fiscais e os riscos identificados nos documentos de apuração periódica da empresa.</p>"""

CORPUS["Rio de Janeiro"] = """<p>O Rio de Janeiro é o único estado brasileiro onde royalties de petróleo compõem parcela significativa do orçamento municipal de dezenas de cidades, e esse fluxo de recursos atrai fornecedoras da cadeia de óleo e gás que instalam filiais na capital para atender a Petrobras, a Shell e as independentes que operam nos campos do pré-sal. O Porto do Rio e o complexo de Itaguaí formam um segundo eixo de atração para operadores logísticos, agentes de carga e tradings que movimentam exportações de minério, açúcar e commodities agrícolas por via marítima.</p>
<p>Fornecedoras de bens e serviços para plataformas offshore escrituram contratos com cláusulas de câmbio e controlam o IOF sobre variação cambial em contratos denominados em dólar, além do regime aduaneiro especial de admissão temporária para equipamentos que retornam à plataforma após manutenção em terra, condição que a Receita Federal fiscaliza pelo cruzamento entre o Radar e o SISCOMEX. Agentes de carga e operadores de armazém alfandegado no Porto do Rio emitem conhecimento de embarque para cada lote de mercadoria e precisam conciliar o ICMS sobre a operação de saída com o PIS e COFINS sobre a receita de armazenagem, calculados em regimes distintos dependendo da natureza do contrato com o exportador. Tradings que compram commodity de produtores rurais para exportação controlam o crédito presumido de PIS e COFINS por tonelada embarcada, crédito que só pode ser aproveitado mediante comprovação de efetivo embarque registrado no SISCOMEX.</p>
<p>Trinta anos de assessoria a estruturas de elevada complexidade formaram uma metodologia de mapeamento que parte dos registros reais da empresa para quantificar o excedente tributário antes de qualquer proposta de honorários.</p>
<p>Para novos clientes do Rio de Janeiro, a avaliação tributária inicial não tem custo e ocorre por videoconferência. O trabalho cobre o enquadramento fiscal em vigor, a auditoria dos créditos do quinquênio e os pontos de fragilidade detectados nos arquivos de apuração periódica da empresa.</p>"""

CORPUS["Joinville"] = """<p>Joinville concentra o maior parque industrial de Santa Catarina, ancorado pela Tupy, referência mundial em fundidos de ferro e alumínio para autopeças, pela Tigre em conexões plásticas, pela Embraco em compressores herméticos e pela Whirlpool em refrigeração doméstica. A presença de empresas desse porte transforma a cidade em polo de fornecedores especializados em usinagem, tratamento superficial e controle dimensional que atendem exigências técnicas equivalentes às de montadoras europeias e norte-americanas.</p>
<p>Fundições e usinadores que fornecem para a cadeia automotiva global precisam atender requisitos de rastreabilidade de lotes que cruzam com a escrituração fiscal: cada peça tem código de produto, peso e composição que determinam a alíquota de ICMS-SC aplicável na saída e a base de cálculo do ICMS em caso de exportação indireta via trading company. Fabricantes de compressores herméticos e refrigeradores que exportam para a União Europeia precisam comprovar a origem brasileira de cada componente para aproveitar os benefícios de isenção fiscal previstos nos acordos comerciais bilaterais, e essa comprovação passa pela escrituração correta do conteúdo regional na nota fiscal de exportação. O porto de São Francisco do Sul, principal ponto de embarque do polo Norte Catarinense, opera sob regras alfandegárias específicas para carga frigorificada e equipamentos em fase de testes que geram obrigações acessórias distintas das exportações convencionais.</p>
<p>A prática de três décadas com indústrias de alta complexidade técnica consolidou uma metodologia para mapear passivos fiscais silenciosos e direitos tributários não aproveitados com base na escrituração real da empresa.</p>
<p>Novos clientes de Joinville recebem uma avaliação tributária gratuita por videoconferência. O trabalho cobre o regime de tributação em vigor, a revisão dos últimos cinco anos de apuração e os pontos de vulnerabilidade fiscal identificados nos registros contábeis da empresa.</p>"""

CORPUS["Campinas"] = """<p>Campinas abriga o maior volume de patentes depositadas no INPI por empresas do interior paulista, reflexo de um ecossistema científico formado pela Unicamp, pela EMBRAPA e pelo CPqD que gerou spin-offs de semicondutores, sistemas embarcados e soluções de agri-tech ao longo de quatro décadas. O eixo petroquímico de Paulínia, com a refinaria da Petrobras e unidades da Dow e da Basf, conecta esse ambiente de inovação a uma cadeia de fornecimento de insumos industriais com escala de exportação.</p>
<p>Spin-offs universitários que captam recursos da FINEP por chamada de subvenção econômica precisam separar a verba de custeio da verba de capital no plano de contas: custeio transita pelo resultado e compõe a base de IRPJ e CSLL, capital é controlado no ativo imobilizado e tem depreciação fiscal diferente da contábil, distinção que a Receita Federal verifica no cruzamento entre a ECF e os relatórios de prestação de contas enviados à agência de fomento. Refinaria e fornecedoras de insumos petroquímicos de Paulínia escrituram o ICMS-SP com benefícios de diferimento concedidos por regime especial: cada remessa de nafta ou petroquímico básico para o polo de ABC tem CFOP e alíquota específicos que mudam conforme o tipo de destinatário, e a aplicação do código errado gera estorno de crédito que aparece somente na auditoria eletrônica da Sefaz. Distribuidoras de insumos agropecuários do eixo Campinas-Americana que revendem para produtores rurais de outros estados apuram o ICMS com substituição tributária e precisam acompanhar a pauta de valores de base de cálculo publicada por cada estado de destino, porque a pauta varia por mês e a nota com base defasada gera auto de diferença de cálculo no estado receptor.</p>
<p>Trinta anos de trabalho com contribuintes de perfil heterogêneo geraram uma base técnica para mapear o tributo pago além do necessário com precisão operacional.</p>
<p>Para novos clientes de Campinas, a triagem fiscal inicial é gratuita e ocorre por videoconferência. O escopo abrange o enquadramento atual, os créditos acumulados nos últimos sessenta meses e as falhas de escrituração detectadas nos arquivos digitais da empresa.</p>"""

if __name__ == "__main__":
    # Quando chamado diretamente, re-valida o corpus interno (deve ser tudo < 0.20 entre si)
    cities = list(CORPUS.keys())
    print("=== Validação cruzada do corpus ===")
    all_ok = True
    for i in range(len(cities)):
        for j in range(i+1, len(cities)):
            score = jaccard(CORPUS[cities[i]], CORPUS[cities[j]])
            status = "OK" if score < 0.20 else "FALHOU"
            if score >= 0.20:
                all_ok = False
            print(f"  {cities[i]:<20} vs {cities[j]:<20} {score:.3f}  {status}")
    print(f"\n  Corpus: {'consistente' if all_ok else 'INCONSISTENTE — revisar'}")
