#!/usr/bin/env python3
# jaccard-corpus.py
# Corpus de CONTEXT_LOCAL aprovados — usado para validar Jaccard de novas cidades.
# Regra: nova cidade precisa ter Jaccard < 0.20 contra TODOS os textos abaixo.
# Adicionar novo entry aqui após cada LP aprovada.

import re

def tokenize(text):
    text = re.sub(r'<[^>]+>', ' ', text)
    text = text.lower()
    return set(re.findall(r'[a-záàâãéêíóôõúüç]+', text))

def jaccard(a, b):
    sa, sb = tokenize(a), tokenize(b)
    return len(sa & sb) / len(sa | sb)

def check(candidate_text, candidate_name="Nova cidade"):
    results = []
    ok = True
    for name, text in CORPUS.items():
        j = jaccard(candidate_text, text)
        status = "OK" if j < 0.20 else "FALHOU"
        if j >= 0.20:
            ok = False
        results.append((name, j, status))
    print(f"\n=== Jaccard: {candidate_name} ===")
    for name, j, status in sorted(results, key=lambda x: -x[1]):
        print(f"  vs {name:<25} {j:.3f}  {status}")
    print(f"  Resultado geral: {'OK — pode publicar' if ok else 'FALHOU — reescrever'}")
    return ok

# ---------------------------------------------------------------------------
# CORPUS APROVADO
# ---------------------------------------------------------------------------

CORPUS = {}

CORPUS["Pará de Minas"] = """<p>Pará de Minas construiu sua economia sobre dois pilares complementares: a indústria de transformação e um comércio varejista que serve toda a região Oeste de Minas. O polo industrial concentra metalurgia, laticínios, indústria química e têxtil — setores que respondem por mais de 40% do PIB municipal. O comércio, por sua vez, atrai consumidores de dezenas de municípios vizinhos, tornando a cidade referência regional em serviços.</p>
<p>Para o empresário local, esse perfil gera desafios tributários específicos. Metalúrgicas acumulam créditos de IPI sobre insumos que raramente são aproveitados. Laticínios operam com substituição tributária de ICMS que, se mal gerida, resulta em pagamento duplo. Empresas de comércio varejista perdem competitividade quando o regime tributário não é calibrado para o seu faturamento real.</p>
<p>A AC Contabilidade nasceu em Pará de Minas em 1996 e cresceu junto com o tecido empresarial da cidade. Três décadas acompanhando comércio, serviços e indústrias locais traduzem-se em capacidade de identificar, com precisão, onde cada tipo de empresa paga tributo além do necessário — e como recuperar esse valor dentro da legalidade.</p>
<p>O escritório fica na Rua Major Fidélis, 244, no Centro de Pará de Minas. O atendimento pode ser presencial ou por videoconferência para empresas de outras cidades. Para novos clientes, o diagnóstico tributário gratuito é o ponto de partida.</p>"""

CORPUS["Sete Lagoas"] = """<p>Sete Lagoas construiu sua identidade econômica sobre o ferro. O Distrito Industrial, inaugurado em 1974, reuniu fundições, siderúrgicas e metalúrgicas que transformaram a cidade no maior polo siderúrgico do interior mineiro. Empresas como a Iveco, que fabrica veículos pesados no município, e grandes marcas do setor de alimentos como Ambev e Itambé instalaram operações que elevaram a cidade à 12ª maior economia de Minas Gerais.</p>
<p>Siderúrgicas que processam ferro-gusa gerado localmente têm direito a crédito de IPI na saída de semiacabados para outras plantas, mas esse fluxo raramente é escriturado com precisão suficiente para aproveitamento integral. Fundições de peças brutas com geometria específica precisam classificar corretamente no NCM cada produto saído, e uma divergência de subposição resulta em autuação com multa proporcional ao valor das notas. Frigoríficos e laticínios do corredor alimentar de Sete Lagoas calculam substituição tributária sobre pauta estadual que muda por ato normativo trimestral, sem notificação prévia ao contribuinte.</p>
<p>Desde 1996, a AC Contabilidade registra cada ciclo do Distrito Industrial de Sete Lagoas: a expansão das fundições na virada do milênio, a reestruturação do ICMS mineiro e a diversificação rumo ao segmento farmacêutico. Essa memória setorial permite construir estratégias tributárias calibradas para a realidade concreta do polo, não para um modelo teórico genérico.</p>
<p>Para novas empresas de Sete Lagoas, a análise tributária inicial não gera custo nem obrigação de vínculo. A reunião de apresentação acontece em formato presencial na sede em Pará de Minas ou por chamada de vídeo, no horário mais conveniente para a rotina industrial.</p>"""

CORPUS["Montes Claros"] = """<p>Montes Claros consolidou-se como centro econômico do Norte de Minas, 5ª maior cidade do estado com PIB de R$ 10,8 bilhões. A estrutura produtiva integra farmacêuticas multinacionais (Nestlé, Novo Nordisk, Eurofarma, MSD), laticínios de escala global (maior produtor de leite condensado do mundo), têxtil e um eixo comercial que abastece o semiárido nordestino. Essa diversidade industrial gera volume fiscal que exige contabilidade de elevada complexidade técnica.</p>
<p>Farmacêuticas multinacionais têm regimes de PIS e COFINS com alíquotas não cumulativas que geram direitos a ressarcimento raramente explorados por escritórios convencionais. Laticínios e alimentos processados operam com ICMS-ST calculado sobre pautas fiscais que mudam por decreto estadual, e quando mal monitoradas resultam em recolhimento acima do real, criando passivo silencioso. Tecelagens que exportam tecidos técnicos para mercados globais precisam controlar o diferencial de alíquota de ICMS e usar o benefício de suspensão com base em registros de embarque corretos.</p>
<p>A AC Contabilidade está no Norte de Minas desde 1996. Nesse tempo acompanhamos a ZFM farmacêutica ganhar corpo, o ICMS-ST ser reformulado e o setor de serviços superar a indústria no PIB local. Acumular vivência setorial significa reconhecer padrões que escritórios recentes não enxergam.</p>
<p>O formato de reunião se adapta à rotina do cliente. Quem está em Montes Claros pode optar por videoconferência, eliminando deslocamento. Quem prefere presencial tem o escritório de Pará de Minas como referência. O ponto de entrada é sempre o mesmo: levantamento completo e gratuito que mapeia tributação vigente, créditos não utilizados nos últimos cinco anos e vulnerabilidades na apuração.</p>"""


CORPUS["Uberaba"] = """<p>Uberaba é a capital genética do mundo: o município exporta embriões e sêmen de zebuínos para mais de 80 países, centraliza os principais leilões da raça Nelore e abriga a maior feira de gado bovino das Américas, a ExpoZebu. Esse eixo agropecuário sustenta um ecossistema de empresas rurais, veterinárias, laboratórios de reprodução e agroindústrias cujas obrigações fiscais vão muito além do ITR e do Funrural típicos do produtor rural.</p>
<p>Pecuaristas com operações de exportação de material genético precisam controlar o tratamento cambial da receita em moeda estrangeira, a isenção de ICMS nas saídas interestaduais para exportação e o crédito de PIS/COFINS sobre insumos veterinários. Frigoríficos e laticínios do entorno operam com crédito presumido de PIS/COFINS da agroindústria, cuja apuração incorreta compromete dezenas de pontos de margem. Distribuidoras atacadistas que servem o varejo regional enfrentam o ICMS-ST sobre alimentos com pautas fiscais que mudam por portaria estadual sem aviso prévio.</p>
<p>O setor pecuário e agroindustrial tem uma particularidade fiscal que o diferencia de outros setores: boa parte dos benefícios tributários depende de prova de destinação. Crédito presumido de PIS/COFINS para frigoríficos exige nota de entrada com peso e espécie corretos. Isenção de ICMS na saída para exportação depende de registro de embarque válido no SISCOMEX na data certa. Quando esses registros têm inconsistência, o benefício cai retroativamente e a empresa descobre o problema numa fiscalização, não numa rotina contábil. Três décadas de atuação com agroindústrias mineiras criaram um protocolo de verificação desses pontos antes que eles se tornem passivo.</p>
<p>Empresas do setor pecuário, frigorífico e agroindustrial de Uberaba podem solicitar uma análise preliminar sem compromisso. A conversa ocorre por chamada de vídeo ou em visita à sede em Pará de Minas. O ponto de partida é o tipo de produto comercializado, o destino das vendas (interno ou exportação) e o tratamento atual dado ao crédito presumido de PIS/COFINS na escrituração mensal.</p>"""

CORPUS["Uberlândia"] = """<p>Uberlândia consolidou-se como quarta maior economia do interior brasileiro, com PIB de R$ 43,5 bilhões, sustentado por convergência de três rodovias federais (BR-050, BR-365 e BR-452) que a posicionam como hub de distribuição para o Cerrado, Sudeste e Centro-Oeste. O Distrito Industrial concentra unidades de Cargill, Sadia, Coca-Cola, Monsanto e Petrobras, irradiando demanda por logística especializada, comércio atacadista de alimentos processados, insumos agrícolas e combustíveis com estruturas tributárias complexas.</p>
<p>Distribuidoras e traders agrícolas operam com regime de substituição tributária em cascatas de ICMS que variam por origem de mercadoria e destino final, gerando créditos represados quando a apuração mensal não acompanha as mudanças de NCM ou de convênio ICMS. Transportadoras acumulam diferenças de alíquota entre a compra de veículos pesados em regime normal e a retenção na folha de motoristas autônomos, sem integração clara entre os saldos. Atacadistas próximos do limite do Supersimples evitam simulação de reenquadramento por falta de expertise em legislação setorial, deixando créditos represados ao alcance de recuperação.</p>
<p>A AC Contabilidade é especializada em regimes tributários do Triângulo Mineiro, com três décadas de acompanhamento a distribuidoras, transportadoras e atacadistas do interior de MG. A metodologia de revisão fiscal retroativa cobre cinco anos de escrituração, identificando valores pagos além do devido e quantificando a recuperação possível antes de qualquer proposta formal.</p>
<p>Novos clientes de Uberlândia recebem diagnóstico sem custo inicial, agendado por chamada remota ou reunião presencial em Pará de Minas. O levantamento cobre regime tributário vigente, saldo de crédito represado e pontos de risco na apuração mensal.</p>"""

CORPUS["Poços de Caldas"] = """<p>Poços de Caldas combina indústria de cerâmica técnica, mineração de alumínio e turismo de alto padrão, com PIB de R$ 4,5 bilhões e fluxo anual de mais de 300 mil visitantes. A Novelis referina alumínio em processo de transformação que alimenta fundições de peças aeroespaciais, e a altitude de 1.200m da cidade atrai laboratórios de pesquisa e centros de inovação de multinacionais que buscam clima ameno e infraestrutura de saúde de referência.</p>
<p>Cerâmicas técnicas e aluminárias classificam produtos por NCM, e essa codificação determina diretamente a alíquota de IPI. Quando a Tabela TIPI é atualizada por decreto e a empresa não revisa a classificação, o tributo recolhido diverge do correto por anos, gerando crédito represado e risco de autuação retroativa. Estabelecimentos hoteleiros de Poços calculam ISS sobre hospedagem com alíquota municipal específica, retendo IRRF em notas para tomadores corporativos conforme lei complementar municipal, dois procedimentos que geram inconsistência quando não segregados na nota fiscal original. Mineradoras que extraem alumínio refratário operam com crédito de PIS e COFINS sobre insumos adquiridos, regime que exige segregação contábil entre produção e estoque para não gerar saldo negativo indevido.</p>
<p>A AC Contabilidade completou trinta anos acompanhando empresas do Sul de Minas. Essa vivência cobre cerâmica, hotelaria, mineração e tecnologia com base em casos reais que diferencia análise precisa de orientação genérica.</p>
<p>Novos clientes de Poços de Caldas iniciam com mapeamento tributário gratuito por videoconferência. O diagnóstico abrange modalidade atual, créditos represados dos últimos cinco anos e vulnerabilidades nas obrigações periódicas.</p>"""

CORPUS["Betim"] = """<p>Betim consolidou-se como segundo maior polo industrial de Minas Gerais com PIB de R$ 33,1 bilhões, sustentado pela maior fábrica da Stellantis na América Latina, pelo Polo Petroquímico de Minas e por 119,7 mil empregos diretos. A cadeia de fornecedores automotivos que orbita a planta inclui centenas de empresas especializadas em autopeças, sistemas de transmissão e logística com obrigações fiscais de alta complexidade.</p>
<p>Fornecedores da indústria automotiva operam com drawback para insumos importados, crédito presumido de IPI sobre componentes internos e regimes especiais de ICMS que exigem domínio técnico profundo. Empresas do polo petroquímico acompanham variações de NCM e pauta fiscal do ICMS-ST em matérias-primas que mudam de classificação por ato normativo, e falhas nesses controles geram acúmulo silencioso de crédito sem benefício de caixa.</p>
<p>Quem trabalha com a cadeia automotiva mineira por décadas aprende que o problema tributário raramente é isolado: a classificação errada de um componente no NCM contamina a cadeia de drawback, que por sua vez afeta o crédito presumido de IPI e, no final, o cálculo do ICMS-ST na saída para a montadora. A AC Contabilidade acumulou esse tipo de conhecimento encadeado ao longo de trinta anos, o que permite localizar o ponto de origem do problema, não apenas sua manifestação mais visível no balanço.</p>
<p>Fornecedores automotivos e petroquímicos de Betim que queiram entender sua posição tributária real podem iniciar uma conversa sem comprometimento financeiro. O primeiro contato é por chamada de vídeo ou pessoalmente na sede em Pará de Minas. O foco é simples: entender o tipo de operação que cada empresa faz, quais regimes especiais estão ativos e onde o ciclo fiscal atual pode estar gerando perda silenciosa de caixa.</p>"""

CORPUS["Curitiba"] = """<p>Curitiba concentra as cinco maiores montadoras do Brasil: Renault S/A com 180 mil veículos/ano, Volkswagen Caminhões com chassis para 40+ países, Volvo Trucks com sistemas de driveline de peso pesado, New Holland com tratores de exportação, e Positivo Informática com servidores fabricados para data centers no Mercosul. O ecossistema paranaense de manufatura em 2025 faturou R$ 87 bilhões, com 62% em operações de exportação via SISCOMEX para América do Norte, Europa e Oceania. Essa magnitude de fluxo tributário exige domínio técnico em crédito de IPI segregado por linha de montagem, controle de ICMS suspenso em componentes importados, e recolhimento correto de IPI em operações de remontagem.</p>
<p>Montadoras que recebem chassis no Paraná para remontagem final enfrentam crédito de IPI limitado conforme o grau de agregação nacional, com verificação anual da Receita Federal sobre se a segregação entre importação e transformação nacional foi feita corretamente. Fabricantes de TI que vendem software em modelo SaaS recebem receita de clientes em São Paulo, Santa Catarina, Minas Gerais e exterior, cada operação com regime tributário distinto: ISS em Curitiba sobre licença local, ICMS suspenso se software é ativo imobilizado corporativo, e zero tributação se venda é para empresa no exterior com faturamento em moeda estrangeira. Empresas de eletroeletrônicos que exportam servidores e computadores montados aproveitam suspensão de ICMS/IPI na aquisição de hard disk, memória RAM e chassis apenas se comprovam embarque via NFe-e e SISCOMEX com data de saída anterior à nota fiscal de venda, qualquer inconsistência gera recolhimento retroativo.</p>
<p>Trabalhar desde 1996 com montadoras, sistemistas e empresas de TI do Paraná consolidou visão precisa de como segregar receita automotiva por componente nacional versus importado, como estruturar retenção de ISS em operações multiestaduais de software SaaS, e como documentar suspensão de tributos em operações de exportação de eletroeletrônicos para não gerar passivo em auditoria.</p>
<p>Empresas manufatureiras de Curitiba que queiram auditar sua tributação agendam avaliação inicial gratuita por videoconferência ou encontro em Pará de Minas. O diagnóstico abrange regime tributário vigente conforme segmento de receita (montagem, componente, software, eletrônica), aproveitamento de crédito de IPI nos cinco exercícios anteriores, controle de ICMS suspenso em importação de componentes, e vulnerabilidades em operações de exportação via SISCOMEX.</p>"""

CORPUS["Sorocaba"] = """<p>Sorocaba estruturou seu parque produtivo ao longo da ferrovia que interliga Santos a Bauru, e hoje esse legado industrial se expressa em plantas de equipamentos elétricos de média e alta tensão, tecelagens técnicas, linhas de produção farmacêutica e fabricantes de autopeças que tornam a cidade a quarta maior economia do interior paulista. A diversidade de setores num mesmo perímetro urbano significa que obrigações fiscais com lógicas completamente distintas coexistem a poucos quarteirões de distância.</p>
<p>Fabricantes de equipamentos elétricos de alta tensão precisam classificar cada produto por TIPI para determinar se a saída é tributada, imune ou sujeita a alíquota reduzida de IPI: uma classificação incorreta gera estorno de crédito ou multa proporcional conforme o sentido do erro. Tecelagens técnicas que exportam tecidos especializados para o mercado têxtil global calculam o benefício de suspensão de tributos na aquisição de fios, mas o controle do saldo exportado por partida é o que determina se a suspensão se converte em isenção definitiva. Indústrias farmacêuticas instaladas no Distrito Industrial de Além Ponte operam com regimes de PIS e COFINS por alíquota diferenciada de produto, e qualquer divergência entre o regime declarado e o efetivamente praticado gera inconsistência que a Receita Federal detecta na cruzagem entre a EFD-Contribuições e a NFe.</p>
<p>A prática de três décadas com empresas da indústria de transformação formou uma base de conhecimento setorial que permite detectar, com precisão, onde cada tipo de operação acumula carga tributária além do que a legislação exige.</p>
<p>Novos clientes de Sorocaba passam por uma triagem tributária gratuita conduzida à distância. A avaliação cobre o regime de tributação atual, o aproveitamento de crédito dos cinco exercícios anteriores e os pontos de atenção identificados nas declarações periódicas da empresa.</p>"""

CORPUS["Guarulhos"] = """<p>Guarulhos é o segundo maior município do estado de São Paulo com PIB de R$ 30 bilhões, ancorado no Aeroporto Internacional de Cumbica, que movimenta 1,5 milhão de toneladas anuais. Centenas de empresas de importação, trading, despacharia aduaneira e logística instalaram-se na cidade para controlar fluxos de carga de todos os continentes, beneficiando-se da proximidade com Anhanguera, Dutra e Imigrantes. Essa concentração de operações de comércio internacional criou ecossistema tributário próprio, onde fiscalidade de importação cruzada com ISS municipal gera inconsistências que órgãos estaduais e municipais detectam em auditorias rotineiras.</p>
<p>Importadoras que recebem mercadoria do exterior precisam classificar cada item no NCM com precisão para determinar a alíquota de IPI correta, pois divergência na subposição resulta em multa por diferença de tributação sobre o valor da nota. Operadores logísticos que prestam serviço de armazenagem, consolidação de carga e despacharia aduaneira escrituram ISS com alíquota que varia conforme tipificação municipal da atividade, e o cruzamento entre ISS do prestador (Guarulhos) e retenção do tomador (em outro estado) frequentemente gera saldo de crédito retido que prescreve se não for recuperado administrativamente. Trading companies que revendem mercadoria importada para varejistas por todo o Brasil precisam controlar o ICMS da operação de saída em cada estado de destino, incluindo diferenças de alíquota entre origem e destino que geram obrigação de diferencial de alíquota não integrada corretamente à apuração.</p>
<p>Trabalhar por décadas com importadoras e operadores do Aeroporto de Cumbica significa conhecer os padrões de autuação da Receita Federal paulistana: qual tipo de reclassificação de NCM ela prioriza em cada ciclo, quais códigos de DI concentram maior frequência de glosa e como a Prefeitura de Guarulhos trata divergências de ISS quando o tomador está em outro estado. Esse tipo de conhecimento operacional não se encontra em norma publicada, mas se acumula em quem lida com esses casos repetidamente.</p>
<p>Importadoras e prestadores de serviço aeroportuário que queiram uma leitura preliminar do risco tributário podem entrar em contato por chamada remota, sem honorários nessa etapa. A conversa inicial foca no perfil de operações de importação, nos NCMs com maior volume de movimentação e nos pontos onde o ISS municipal e a retenção na fonte criam divergências na apuração.</p>"""

CORPUS["Manaus"] = """<p>Manaus é a maior economia da Amazônia brasileira com PIB de R$ 85 bilhões, sustentada pela Zona Franca de Manaus (ZFM), regime tributário criado em 1967 que oferece isenção de Imposto de Importação, desoneração de IPI para manufaturados no Polo Industrial, ICMS reduzido nas remessas interestaduais e PIS/COFINS diferenciado em determinados segmentos. Mais de 500 empresas operam plantas habilitadas na ZFM, concentradas em eletroeletrônicos de consumo (Sony, Samsung, LG, Positivo, Philips), motocicletas (Honda, Yamaha), refrigeração e equipamentos de telecomunicação que fabricam componentes importados para abastecimento de toda a América do Sul. A cidade representa 5% do PIB industrial brasileiro, proporção que torna a contabilidade da ZFM um diferencial competitivo para qualquer empresa operando ali.</p>
<p>Cada empresa da ZFM deve manter Processo Produtivo Básico comprovado para cada linha de produtos e arquivo segregado de habilitação junto à Superintendência da Zona Franca (SUFRAMA), com auditoria annual pela Receita Federal que verifica conformidade de PPB, volumes de produção e desvios de destinação. Qualquer inconsistência entre laudos de PPB e produção efetiva resulta em glosa retroativa de até cinco anos com perda de incentivos e multa proporcional, situação que força empresas a manter documentação impecável. Empresas que operam fora do Polo mas dentro da ZFM (distribuidoras, prestadoras de serviço, operadores logísticos) não usufruem isenção de IPI, mas podem aproveitar crédito presumido de PIS/COFINS reduzido se enquadradas corretamente em atividade específica de comércio exterior, benefício que raramente é mapeado com precisão.</p>
<p>O histórico de trabalho da AC Contabilidade inclui ciclos inteiros de revisão de Processo Produtivo Básico junto a fabricantes de televisores e motocicletas no Polo Industrial. Cada revisão ensinou uma lição diferente sobre como a SUFRAMA interpreta o conceito de valor agregado local, quais registros de rastreabilidade são aceitos em fiscalização e em quais situações o benefício pode ser suspenso retroativamente por falha documental. Esse repertório específico do PIM não é replicável por escritórios sem presença direta em casos amazônicos.</p>
<p>Fabricantes e fornecedores instalados no PIM podem solicitar um levantamento preliminar do perfil tributário sem honorários. O trabalho começa por leitura do portfólio de produtos habilitados, comparação com os PPBs em vigor e mapeamento das inconsistências entre o que foi declarado ao Fisco Federal e o que os registros de produção mostram. A reunião para apresentar esses achados é feita por chamada de vídeo ou em visita presencial à sede em Pará de Minas.</p>"""

CORPUS["Osasco"] = """<p>Osasco representa a maior concentração de serviços financeiros no interior paulista, com PIB per capita que supera São Paulo capital. A cidade sedeia matriz de bancos de médio porte (Bradesco é operado de lá), holdings de serviços financeiros, cooperativas de crédito, administradoras de consórcio e fintechs que se instalaram pela proximidade com a Marginal Pinheiros, infraestrutura de telecomunicações de latência ultra baixa e acesso a agências corporativas. O bairro Alphaville consolidou-se como distrito de sedes empresariais e centros de serviços especializados com receita em múltiplos estados, expandindo a complexidade tributária além de varejo financeiro de âmbito local.</p>
<p>Holdings financeiras que operam operações de mútuo entre empresas do mesmo grupo defrontam-se com IOF incidente sobre esses fluxos com tratamento distinto conforme vencimento da operação, e falhas no registro dessa operação resultam em inconsistência entre o lançamento contábil e a escrituração fiscal do D-MAS. Bancos e instituições de crédito incorrem em deduções de juros que são limitadas por normas de capital, e essas limitações impactam no cálculo de IRPJ e CSLL de maneira que requer integração entre contabilidade fiscal e auditoria interna de risco. Prestadores de serviços corporativos (consultoria, assessoria jurídica, auditoria) que recebem de tomadores em outros estados enfrentam ISS conflitante entre competência municipal do tomador versus do prestador, situação que órgãos municipais paulistas exploram em cruzagem de bases.</p>
<p>A AC Contabilidade está presente desde 1996 em estruturas fiscais de instituições financeiras e holdings. Esse acervo de casos reais permite mapear operações de IOF, créditos tributários em operações interbancárias e riscos em receitas multiestaduais de forma que nenhum escritório generalista consegue replicar.</p>
<p>Empresas de Osasco que desejam revisar sua posição tributária recebem diagnóstico inicial gratuito por videoconferência ou em pré-reunião presencial. O levantamento cobre regime atual, aproveitamento de crédito acumulado nos últimos cinco anos e inconsistências identificadas nas obrigações acessórias de natureza financeira.</p>"""

CORPUS["Caxias do Sul"] = """<p>Caxias do Sul é o maior polo metal-mecânico do Brasil com PIB de R$ 28 bilhões, cristalizado na especificação de carrocerias rodoviárias (Marcopolo, Randon) que atendem montadoras em cinco continentes. A marca Marcopolo exporta chassis personalizados para operadores de transporte de passageiros em 100+ países, e essa escala global de exportação direta criou cadeia de fornecedores de peças usinadas, suspensões especiais e sistemas integrados que precisam controlar conformidade tributária em operações multibandeira. Paralelo ao setor automotivo pesado, a vinicultura gaúcha (AURORA, Peterlongo, Miolo, vinícolas independentes) representa 18% do PIB e concentra-se em bebidas para exportação, com regimes tributários segregados por categoria: vinhos finos, vinhos tinto/branco, espumante refrigerado, destilado, cada um com pauta de ICMS-ST distinta mantida pela Sefaz-RS com granularidade que nenhuma outra região oferece.</p>
<p>Fabricantes de carrocerias que exportam chassis completo para montagem final em país de destino precisam cumprir laudos de conteúdo agregado (mínimo de valor agregado brasileiro) para aproveitar benefícios de redução de IPI, além de controlar a classificação NCM de cada subconjunto usinado que sai da fábrica. Vinícolas que vendem bebida para supermercados em São Paulo, Santa Catarina e Paraná enfrentam ICMS-ST com base de cálculo em pauta estadual que muda por portaria trimestral: quando a portaria é publicada retroativamente ou com validade anterior à publicação, o contribuinte fica com inconsistência de cálculo que só aparece em auditoria da Sefaz. Operadores logísticos que preparam cargas de carroceria para contêiner e embarque em porto via SISCOMEX precisam segregar ICMS-ST de importação temporária de peças de reposição que retornam da manutenção no exterior.</p>
<p>Trabalhar com metal-mecânica gaúcha ao longo de três décadas significa ter acompanhado pelo menos duas recessões industriais, três alterações de regime do ICMS no Rio Grande do Sul e as oscilações do câmbio que afetam toda empresa que fatura em dólar. Essa trajetória acumulou casos reais de como a Sefaz-RS trata a pauta de ICMS-ST em bebida fora do prazo, de como o laudo de conteúdo agregado é verificado em fiscalização de carroceria exportada e de como o crédito presumido de IPI é calculado quando o chassis tem componentes importados misturados com nacionais.</p>
<p>Fabricantes da Serra Gaúcha interessados em revisar sua posição fiscal encontram na AC Contabilidade um interlocutor que conhece o perfil de exportação da região, as particularidades do ICMS gaúcho e os incentivos fiscais do RS para a indústria de transformação. O primeiro contato não tem custo. A conversa inicial ocorre por chamada de vídeo, com escopo centrado no perfil de faturamento, nos regimes de exportação ativos e nos controles de NCM que determinam a alíquota correta em cada saída.</p>"""

CORPUS["Fortaleza"] = """<p>Fortaleza é a quinta maior economia do Brasil e lidera o setor de moda do Nordeste: indústrias como Marisol, Riachuelo e Guararapes transformam a capital cearense em referência global de confecção, bordados e têxtil. A economia local não depende só da moda. O Porto do Pecém, integrado à Zona de Processamento de Exportação (ZPE-CE), atrai investimento em petroquímica, siderurgia e comércio exterior. Paralelamente, a cidade consolidou-se como hub regional de call centers, TI e serviços de business process outsourcing (BPO) que servem empresas de toda a América Latina. Três eixos produtivos distintos convergem num único perímetro fiscal.</p>
<p>Fabricantes de confecção que operam dentro da ZPE-CE usufruem isenção de ICMS nas operações internas e suspensão de IPI, mas precisam manter escrituração segregada por habilitação junto à Superintendência da Zona Franca (SUFRAMA) e à Secretaria da Fazenda. Indústrias têxteis que se beneficiam dos incentivos SUDENE enfrentam um desafio duplo: comprovar que mantêm a contrapartida de emprego e renda conforme termo de concessão, além de calcular corretamente o diferencial de ICMS nas remessas interestaduais quando a mercadoria sai da Zona Franca para outros estados. Centros de BPO e call centers que prestam serviços para tomadores em São Paulo e no Sudeste precisam apurar o ISS conforme o município do cliente final, não o de Fortaleza, combinando isso com o PIS e COFINS não cumulativos sobre receita de serviço, dois regimes que raramente são integrados corretamente.</p>
<p>A AC Contabilidade acompanha desde 1996 a transformação econômica de Pará de Minas e, ao longo de três décadas, desenvolveu metodologia especializada em incentivos fiscais regionais, regimes de zona franca e tributação de serviços de exportação. Essa vivência permitiu construir um repertório preciso para empresas que operam sob benefícios estaduais e federais sem comprometer a auditoria interna de órgãos de controle.</p>
<p>Para novas empresas de Fortaleza, a consulta tributária inicial é gratuita e ocorre integralmente por videoconferência. O diagnóstico abrange enquadramento na ZPE ou SUDENE, aproveitamento de créditos dos últimos cinco anos, e identificação de passivos silenciosos na escrituração periódica.</p>"""

CORPUS["Goiânia"] = """<p>Goiânia comanda um PIB de R$ 68 bilhões por ano, sendo o maior vetor econômico do Centro-Oeste. A cidade funciona como capital de três setores simultâneos que demandam contabilidade bifurcada: operadoras de planos de saúde reguladas pela ANS com obrigação de segregação contábil por produto (ambulatorial, hospitalar, odontológico), frigoríficos e distribuidoras de carnes que movimentam ICMS-ST em cascata por estado de origem do gado, e tradings que exportam soja, milho e algodão com regimes diferenciados de pis e COFINS. Cada segmento funciona sob lógica tributária diversa, requerendo diagnóstico inicial para evitar enquadramento indevido que gera multa retroativa por cinco anos.</p>
<p>Operadoras de planos de saúde em Goiânia enfrentam dois desafios críticos: sinistralidade variável por produto força reclassificação anual do regime tributário (pode ser lucrativo em ano X e deficitário em X+1, alterando PIS/COFINS), e a segregação contábil obrigatória pela ANS não coincide com as divisões que a Receita Federal reconhece para fins de apuração de PIS diferenciado. Frigoríficos e distribuidoras de carnes precisam dominar o fluxo ICMS-ST entre estados de criação (origem baixa alíquota) e estado de industrialização (GO, alíquota integral), mais a apuração de ICMS diferencial para operações interestaduais. Exportadores diretos de grãos operam com PIS/COFINS zero, porém precisam documentar a condição de exportador efetivo perante a Receita Federal, discriminando transferências interestaduais de mercadoria (que geram ICMS diferencial) de operações de exportação (que são zero).</p>
<p>Desenvolvemos um protocolo de diagnóstico estruturado para cada ramo: ASOs (Ações Sindicais Obrigatórias) de saúde ocupam 45 minutos; frigoríficos ocupam 60 minutos de mapeamento de CFOP por estado de origem; exportadores exigem 90 minutos de análise de fluxo de cambial. A recomendação final é sempre baseada em dados de 24 meses anteriores, nunca em suposições de tendência de mercado.</p>
<p>Clientes novo de Goiânia começam com avaliação técnica sem custo, incluindo: regime tributário vigente (Lucro Real, Presumido ou Simples), mapa de documentos fiscais dos últimos 24 meses, verificação de conformidade com exigências específicas do setor (ANS segregation, ICMS-ST cascata, exportação zero-PIS), e relatório de pontos críticos e oportunidades legítimas de reorganização fiscal ou aproveitamento de crédito."""

CORPUS["João Pessoa"] = """<p>João Pessoa consolida sua economia no turismo litorâneo de alto padrão, educação superior privada e serviços especializados que extrapolam a capital. Com PIB de R$ 20 bilhões, a cidade atrai resorts de bandeira internacional na orla de Tambaú, universidades privadas referenciadas no Nordeste, hospitais especializados em oncologia e cardioterapia que atendem pacientes de cinco estados. Complementando esse tripé, o Porto Digital Paraíba reúne centros de BPO e call centers que processam operações para clientes de toda a América Latina. A indústria calçadista do interior de Pernambuco mantém filiais de distribuição que movem volume fiscal significativo por meio de serviços de comércio e logística.</p>
<p>Call centers e operadores de BPO que faturam serviços para tomadores em São Paulo, Rio e Brasília enfrentam uma controvérsia tributária específica: o ISS deve ser apurado no município do prestador (João Pessoa) ou no município do tomador do serviço. A Confederação Nacional de Municípios interpreta a norma de forma distinta de cidades individuais, gerando risco de bitributação ou autuação por falta de retenção. Hotéis de bandeira internacional que combinam receita de hospedagem, alimentos e bebidas, estacionamento e serviços de turismo precisam segregar cada atividade numa nota fiscal separada, pois João Pessoa tributa cada item por alíquota distinta. Faculdades privadas que recebem bolsas de estudantes do FIES precisam contabilizar a bolsa como receita isenta de COFINS mas sujeita a PIS em regime específico, distinção que nem todas as EFD conseguem capturar corretamente.</p>
<p>A AC Contabilidade consolidou desde 1996 uma metodologia para empresas de serviços que operam com múltiplas fontes de receita (turismo, educação, BPO), cada uma com regime tributário distinto e risco de autuação municipal. Essa experiência permite identificar onde o ISS está sendo pago de forma incorreta antes que auditorias eletrônicas municipais o sinalizem.</p>
<p>Novos clientes de João Pessoa recebem avaliação tributária sem custo inicial, realizada integralmente por videoconferência. O diagnóstico abrange regime de tributação vigente, segregação correta de receitas por atividade, aproveitamento de créditos do quinquênio e passivos ocultos na escrituração periódica.</p>"""

CORPUS["Ribeirão Preto"] = """<p>Ribeirão Preto centraliza a economia do agronegócio paulista: capital nacional do sucroalcooleiro, a cidade abriga usinas, destilarias e fornecedoras da cadeia canavieira que movimentam bilhões de reais por safra. Ao lado desse eixo produtivo, consolidou-se um complexo hospitalar e de biotecnologia referenciado em toda a América Latina, com hospitais universitários, centros de pesquisa clínica e clínicas oncológicas que atraem pacientes de dezenas de estados brasileiros.</p>
<p>Usinas sucroalcooleiras operam com crédito presumido de PIS/COFINS sobre a receita de etanol hidratado, ICMS com benefícios estaduais específicos para biocombustíveis concedidos pelo Estado de SP e Funrural sobre a produção rural integrada com fornecedores de cana. Hospitais e clínicas oncológicas de médio porte que ultrapassaram o teto do Supersimples precisam avaliar se o Lucro Presumido ou o Lucro Real gera menor carga, considerando a dedutibilidade de despesas médicas previstas na Lei 9.249 e o peso da folha de pagamento de especialistas no cálculo da CSLL. Distribuidoras de insumos agrícolas que transitam entre regimes acumulam crédito de ICMS nas entradas que, quando não escriturado mensalmente, vira ativo tributário represado sem gerar benefício de caixa.</p>
<p>A auditoria retroativa que aplicamos parte da escrituração existente para mapear o saldo credor acumulado em cada setor, quantifica o valor recuperável e apresenta o resultado antes de qualquer proposta de honorários.</p>
<p>O levantamento tributário de entrada é gratuito e ocorre por reunião virtual. O escopo abrange regime vigente, créditos acumulados nos últimos sessenta meses e riscos identificados na escrituração atual.</p>"""

CORPUS["Salvador"] = """<p>Salvador é a maior economia do Nordeste com PIB de R$ 58 bilhões e consolida sua força sobre duas fundações distintas: o Complexo Petroquímico de Camaçari, maior polo integrado de química básica da América Latina com mais de 90 unidades interligadas por dutos de matéria-prima e utilidades compartilhadas (Braskem, BASF, Dow, Monsanto, Ford), e o porto de Aratu, terceira maior movimentação de cargas da Bahia com especialização em granéis sólidos, fertilizantes e químicos. O turismo cultural e litorâneo acrescenta uma terceira camada: a capital baiana recebe dois milhões de visitantes anuais e mantém rede hoteleira que opera em regime de ocupação contínuo.</p>
<p>Fornecedoras de insumos químicos que abastecem o complexo de Camaçari enfrentam um desafio singular de apuração. Transferências internas entre plantas do mesmo grupo econômico exigem CFOP específico que a Sefaz-BA trata com rigor distinto do comércio interestadual comum. Qualquer divergência gera glosa de crédito de ICMS que só transparece em auditoria eletrônica, depois que o prazo de retificação venceu. Indústrias petroquímicas que optam por Lucro Real precisam mapear o IPI sobre insumos importados e o ICMS com diferencial de alíquota para transferências interestaduais de derivados de nafta, cálculos que variam por tipo de destinação (exportação via porto versus transferência interna). Operadores de armazéns e terminais portuários de Aratu controlam simultaneamente ICMS-BA sobre movimentação de mercadorias, PIS e COFINS sobre serviços de armazenagem e retenção de IRRF em contratos com fornecedores.</p>
<p>A familiaridade com Camaçari vem de quase três décadas acompanhando casos reais de petroquímica baiana: CFOPs lançados com código de transferência quando deveriam registrar venda interestadual, glosas de ICMS que se acumularam silenciosamente por exercícios inteiros, e plantas do mesmo grupo econômico que tributavam a transferência interna como se fosse operação ordinária. Cada um desses casos construiu um padrão de reconhecimento que é difícil de desenvolver sem estar imerso na lógica específica da Sefaz-BA.</p>
<p>Interessados em avaliar a posição tributária de sua empresa em Salvador ou Camaçari podem solicitar uma conversa preliminar sem custo. Essa reunião acontece por chamada de vídeo ou presencialmente na sede em Pará de Minas. O ponto de partida é sempre o mesmo: entender o fluxo de operações, os CFOPs em uso e onde a legislação baiana cria obrigações que escritórios de outros estados raramente conhecem com profundidade.</p>"""

CORPUS["Blumenau"] = """<p>Blumenau divide o espaço urbano entre o maior parque têxtil da Região Sul e um polo tecnológico com empresas de software, automação industrial e cibersegurança que faturaram mais de R$ 3 bilhões em 2023. A convivência entre teares jacquard e servidores de computação em nuvem não é apenas curiosidade histórica: ela cria obrigações fiscais com lógicas completamente distintas que convivem no mesmo perfil de contribuinte e exigem tratamento separado por atividade.</p>
<p>Fábricas de confecção do Vale do Itajaí que adotam o regime cumulativo de PIS e COFINS pagam alíquotas menores sobre a receita, mas abrem mão do crédito sobre insumos. Quando o volume de compras de tecido e aviamentos é alto em relação ao faturamento, o regime não cumulativo pode ser mais vantajoso, mas essa análise precisa ser feita com os números reais da empresa, não com estimativas setoriais. Marcas de moda blumenauenses que licenciam estampas e coleções para confeccionistas de outros estados precisam classificar o pagamento como royalty sujeito a IRPJ e CIDE ou como prestação de serviço sujeita a ISS, escolha que impacta diretamente a alíquota efetiva e a forma de retenção na fonte. Empresas de software com contratos de licença recorrente para clientes em municípios de outros estados enfrentam a controvérsia da LC 157/2016 sobre ISS: pagar no destino ou na origem é uma questão que cada prefeitura ainda interpreta à sua forma, gerando risco de bitributação ou de autuação por não retenção.</p>
<p>Três décadas de prática com indústrias de transformação e prestadores de serviços consolidaram uma metodologia para mapear o excedente tributário por atividade antes de propor qualquer ajuste de enquadramento.</p>
<p>Novos clientes de Blumenau recebem uma avaliação fiscal gratuita por videoconferência. O diagnóstico abrange o regime de tributação em vigor, os direitos creditórios dos últimos cinco exercícios e os pontos de inconsistência identificados na escrituração da empresa.</p>"""

CORPUS["Feira de Santana"] = """<p>Feira de Santana é a segunda maior economia da Bahia com PIB de R$ 15 bilhões e funciona simultaneamente como maior hub atacadista do Nordeste e como polo industrial de autopeças e manufatura. A posição geográfica no cruzamento das BR-116 e BR-324 torna a cidade o ponto de passagem obrigatório para mercadorias que chegam de São Paulo e Minas Gerais antes de abastecer o semiárido baiano. O Centro Industrial Subaé reúne fabricantes de autopeças (Ford, Bosch, Pirelli), alimentos processados (Nestlé, frigoríficos) e artigos de couro com exportação para mercados globais. Dois eixos econômicos completamente distintos convergem num perímetro tributário único.</p>
<p>Atacadistas redistribuidores que movem volumes entre estados precisam segregar com rigor o CFOP de transferência interna (entre filiais do mesmo contribuinte) do CFOP de venda interestadual. A Sefaz-BA localiza essas confusões na auditoria eletrônica cruzando as GIAs, gerando glosa de crédito com penalidade. Indústrias do Subaé que exportam autopeças para montadoras do Sul precisam calcular o ICMS-ST sobre insumos importados, gerenciar o drawback parcial para componentes que retornam à importadora, e simultaneamente controlar o DIFAL quando revendem para clientes no varejo de São Paulo. Distribuidoras de alimentos que transitam entre Simples Nacional e Lucro Presumido precisam avaliar antes da opção anual como a mudança impacta o regime de ICMS-ST na Bahia, que trata contribuintes de tamanhos diferentes com alíquotas distintas.</p>
<p>O Subaé tem uma característica que o distingue de outros parques industriais: a combinação de autopeças, alimentos e artigos de couro num mesmo endereço fiscal exige separar drawback de exportação de couro do crédito presumido de PIS/COFINS de frigorífico — dois regimes ativados pelo mesmo evento de nota fiscal mas com tratamento tributário oposto. Quem não faz essa separação na escrituração mensal acumula erro silencioso que só aparece numa verificação externa.</p>
<p>Fabricantes do Subaé, atacadistas e distribuidoras interessados em mapear o risco tributário acumulado entram em contato por chamada remota, sem honorários nessa etapa inicial. A leitura preliminar foca nos drawbacks ativos, no enquadramento de ICMS-ST vigente e nas saídas interestaduais dos últimos vinte e quatro meses — o intervalo onde inconsistências ainda têm margem de correção espontânea.</p>"""

CORPUS["Piracicaba"] = """<p>Piracicaba ocupa uma posição singular no interior paulista: a ESALQ da USP instalada às margens do rio desde 1901 tornou a cidade o principal centro de pesquisa em melhoramento genético de cana-de-açúcar do mundo, e esse legado científico sustenta hoje uma constelação de usinas, destilarias, fornecedores de cana e startups de bioenergia que operam com modelos de receita distintos dos setores industriais convencionais. A metalurgia agrícola voltada para colheitadeiras, prensas de bagaço e sistemas de bombeamento complementa esse perfil com uma base manufatureira de médio porte.</p>
<p>Usinas sucroalcooleiras do entorno de Piracicaba que vendem etanol hidratado para distribuidoras de combustível escrituram o crédito presumido de PIS e COFINS por tonelada de cana processada, mecanismo regulado por instrução normativa com tabela de valores atualizada anualmente pela Receita Federal: a aplicação do coeficiente do ano anterior gera apuração incorreta que se acumula silenciosamente ao longo do exercício. Cooperativas de fornecedores rurais que entregam cana a mais de uma usina dentro do mesmo período de safra precisam emitir nota de produtor para cada destinatário separado e controlar o Funrural por operação, pois o INSS rural incide sobre o valor bruto recebido em cada entrega sem compensação cruzada entre usinas. Fornecedores de peças e subconjuntos para colheitadeiras que atendem montadoras de São Paulo e Minas Gerais emitem nota com alíquota interestadual de ICMS e precisam acompanhar o DIFAL cobrado pelo estado do destinatário para não ser surpreendido com auto de infração estadual.</p>
<p>Três décadas de acompanhamento ao setor sucroalcooleiro e à metalurgia agrícola sedimentaram uma metodologia para mapear o excedente tributário com base nos registros reais da empresa.</p>
<p>Para novos clientes de Piracicaba, a triagem fiscal inicial não tem custo e ocorre por transmissão digital. O levantamento abrange o enquadramento vigente, a revisão dos créditos do quinquênio e as falhas de apuração identificadas nos arquivos periódicos da empresa.</p>"""

CORPUS["Recife"] = """<p>Recife consolida sua posição como capital tecnológica do Nordeste: o Porto Digital reúne mais de 350 empresas de software, games, cibersegurança e serviços digitais que movimentam bilhões em receita anual, com foco em operações para clientes de todos os continentes. Complementando essa base de alta tecnologia, o Complexo Portuário de SUAPE em Ipojuca funciona como o segundo maior porto da região Nordeste, atraindo refinarias, estaleiros, operadores logísticos e traders que movem petróleo, produtos siderúrgicos e grãos em escala multinacional. O município integra beneficiários de SUDAM e SUDENE, o que adiciona uma terceira camada de incentivos fiscais federais à tributação local.</p>
<p>Desenvolvedoras de software do Porto Digital que faturam serviços de licenciamento e consultoria para clientes em outros estados enfrentam simultaneamente a disputa pela alíquota correta de ISS (cada município tributa serviço de TI de forma distinta), a retenção de PIS/COFINS na fonte por tomador em regime não cumulativo e, em caso de faturamento acima de R$ 78 milhões, a obrigação de migração de regime de tributação. Operadores logísticos e terminais portuários de SUAPE que realizam operações de importação precisam segregar o ICMS-ST sobre bens em trânsito do PIS e COFINS sobre armazenagem, além de controlar o Siscomex para exportações indiretas, três sistemas tributários que se cruzam por operação. Refinarias e indústrias navais que usufruem benefícios SUDENE necessitam segregação contábil rigorosa por habilitação junto ao órgão gestor federal e estadual, sob risco de glosa retroativa.</p>
<p>A AC Contabilidade opera há três décadas em regiões com regimes tributários de estrutura complexa, o que gerou familiaridade direta com o raciocínio fiscal aplicado a benefícios SUDENE, Porto Digital e cadeias logísticas portuárias. O resultado prático é a capacidade de reconstruir o histórico de apuração de qualquer empresa do Recife, comparar o que foi recolhido com o que a legislação de incentivo permitia e quantificar numericamente o valor recuperável antes de apresentar qualquer proposta.</p>
<p>Empresas recifenses que queiram auditar seus últimos exercícios fiscais podem solicitar uma leitura prévia sem compromisso financeiro. O contato é feito por chamada de vídeo ou presencialmente na sede em Pará de Minas, e o escopo dessa primeira reunião abrange o enquadramento atual, os documentos de habilitação em vigor junto ao órgão gestor e os pontos de risco no cruzamento entre NFe e obrigações acessórias periódicas.</p>"""

CORPUS["Rio de Janeiro"] = """<p>Rio de Janeiro é a segunda maior economia brasileira com PIB de R$ 300 bilhões, alicerçada na cadeia de petróleo e gás do Atlântico Sul (Petrobras, Shell, Equinor, REPSOL, TotalEnergies). Os campos do pré-sal, descobertos a partir de 2006, transformaram a capital em polo de fornecimento especializado de bens, serviços e engenharia de plataformas offshore que não existiam antes. A Bacia de Campos, a Bacia de Santos e os campos licitados atraem centenas de empresas contratadas para prestar serviços de perfuração, estabilização, metrologia, inspeção submarina, logística de suprimentos de plataforma e operações de manutenção que lidam com complexidade tributária única: royalties federais que circulam na forma de receitas de serviço, preços de transferência de bens sob regime de admissão temporária, e câmbio em operações de longo prazo denominadas em dólar que exigem especialização contábil não transferível.</p>
<p>Prestadores de serviços de engenharia e construção para plataformas recebem receita em contrato fixo com Petrobras ou concessionárias e precisam controlar preço de transferência para insumos importados (tubos especiais, equipamentos de alta pressão, sensores), aproveitando crédito de PIS e COFINS sobre insumos de ativo imobilizado diferenciado conforme o enquadramento de cada componente no NCM. Fornecedoras que realizam manutenção com equipamentos embarcados (de terra para plataforma) precisam de admissão temporária renovada a cada ciclo de manutenção com prazo de retorno documentado no SISCOMEX, e qualquer atraso gera devolução de benefício tributário com juros. Empresas de serviço de logística de suprimentos de plataforma (helicopter, tugs, supply boats) enfrentam IOF sobre pagamentos a fornecedoras internacionais com incidência que varia conforme natureza da operação (câmbio, seguros, demurrage), além de cálculo de PIS e COFINS não cumulativos sobre receita que precisa ser segregada por tipo de serviço prestado.</p>
<p>Vinte e nove anos de escrituração contábil produziram um repertório de situações reais: o fornecedor offshore que perdia a admissão temporária por vencimento de prazo não rastreado; a engenharia naval que calculava preço de transferência tomando o valor CIF ao invés do valor de mercado na data do câmbio; a trading que creditava PIS e COFINS sobre custos de frete internacional sem segregar por modalidade contratual. Cada caso deixou um aprendizado que se tornou parte do protocolo de revisão aplicado em novos clientes cariocas.</p>
<p>Fornecedoras e prestadoras de serviço para a cadeia de óleo e gás no Rio interessadas em revisar sua posição podem iniciar o contato por chamada de vídeo. Não há honorários na primeira etapa. O escopo dessa conversa inicial abrange o tipo de contrato com a operadora, o perfil dos equipamentos sob admissão temporária e os pontos onde a escrituração atual pode estar gerando risco ou retenção desnecessária de caixa.</p>"""

CORPUS["Joinville"] = """<p>Joinville concentra o maior parque industrial de Santa Catarina, ancorado pela Tupy, referência mundial em fundidos de ferro e alumínio para autopeças, pela Tigre em conexões plásticas, pela Embraco em compressores herméticos e pela Whirlpool em refrigeração doméstica. A presença de empresas desse porte transforma a cidade em polo de fornecedores especializados em usinagem, tratamento superficial e controle dimensional que atendem exigências técnicas equivalentes às de montadoras europeias e norte-americanas.</p>
<p>Fundições e usinadores que fornecem para a cadeia automotiva global precisam atender requisitos de rastreabilidade de lotes que cruzam com a escrituração fiscal: cada peça tem código de produto, peso e composição que determinam a alíquota de ICMS-SC aplicável na saída e a base de cálculo do ICMS em caso de exportação indireta via trading company. Fabricantes de compressores herméticos e refrigeradores que exportam para a União Europeia precisam comprovar a origem brasileira de cada componente para aproveitar os benefícios de isenção fiscal previstos nos acordos comerciais bilaterais, e essa comprovação passa pela escrituração correta do conteúdo regional na nota fiscal de exportação. O porto de São Francisco do Sul, principal ponto de embarque do polo Norte Catarinense, opera sob regras alfandegárias específicas para carga frigorificada e equipamentos em fase de testes que geram obrigações acessórias distintas das exportações convencionais.</p>
<p>A prática de três décadas com indústrias de alta complexidade técnica consolidou uma metodologia para mapear passivos fiscais silenciosos e direitos tributários não aproveitados com base na escrituração real da empresa.</p>
<p>Novos clientes de Joinville recebem uma avaliação tributária gratuita por videoconferência. O trabalho cobre o regime de tributação em vigor, a revisão dos últimos cinco anos de apuração e os pontos de vulnerabilidade fiscal identificados nos registros contábeis da empresa.</p>"""

CORPUS["Campinas"] = """<p>Campinas abriga o maior volume de patentes depositadas no INPI por empresas do interior paulista, reflexo de um ecossistema científico formado pela Unicamp, pela EMBRAPA e pelo CPqD que gerou spin-offs de semicondutores, sistemas embarcados e soluções de agri-tech ao longo de quatro décadas. O eixo petroquímico de Paulínia, com a refinaria da Petrobras e unidades da Dow e da Basf, conecta esse ambiente de inovação a uma cadeia de fornecimento de insumos industriais com escala de exportação.</p>
<p>Spin-offs universitários que captam recursos da FINEP por chamada de subvenção econômica precisam separar a verba de custeio da verba de capital no plano de contas: custeio transita pelo resultado e compõe a base de IRPJ e CSLL, capital é controlado no ativo imobilizado e tem depreciação fiscal diferente da contábil, distinção que a Receita Federal verifica no cruzamento entre a ECF e os relatórios de prestação de contas enviados à agência de fomento. Refinaria e fornecedoras de insumos petroquímicos de Paulínia escrituram o ICMS-SP com benefícios de diferimento concedidos por regime especial: cada remessa de nafta ou petroquímico básico para o polo de ABC tem CFOP e alíquota específicos que mudam conforme o tipo de destinatário, e a aplicação do código errado gera estorno de crédito que aparece somente na auditoria eletrônica da Sefaz. Distribuidoras de insumos agropecuários do eixo Campinas-Americana que revendem para produtores rurais de outros estados apuram o ICMS com substituição tributária e precisam acompanhar a pauta de valores de base de cálculo publicada por cada estado de destino, porque a pauta varia por mês e a nota com base defasada gera auto de diferença de cálculo no estado receptor.</p>
<p>Trinta anos de trabalho com contribuintes de perfil heterogêneo geraram uma base técnica para mapear o tributo pago além do necessário com precisão operacional.</p>
<p>Para novos clientes de Campinas, a triagem fiscal inicial é gratuita e ocorre por videoconferência. O escopo abrange o enquadramento atual, os créditos acumulados nos últimos sessenta meses e as falhas de escrituração detectadas nos arquivos digitais da empresa.</p>"""


CORPUS["Ribeirão Preto"] = """<p>Ribeirão Preto centraliza a economia do agronegócio paulista como capital nacional do sucroalcooleiro, abrigando usinas, destilarias e fornecedoras da cadeia canavieira que movimentam bilhões de reais por safra. Ao lado desse eixo produtivo, consolidou-se um complexo hospitalar e de biotecnologia referenciado em toda a América Latina, com hospitais universitários, centros de pesquisa clínica e clínicas oncológicas que atraem pacientes de dezenas de estados brasileiros.</p>
<p>Usinas sucroalcooleiras operam com crédito presumido de PIS e COFINS sobre a receita de etanol hidratado, ICMS com benefícios estaduais específicos para biocombustíveis concedidos pelo Estado de São Paulo e Funrural sobre a produção rural integrada com fornecedores de cana. Hospitais e clínicas oncológicas de médio porte que ultrapassaram o teto do Supersimples precisam avaliar se o Lucro Presumido ou o Lucro Real gera menor carga, considerando a dedutibilidade de despesas médicas previstas na Lei 9.249 e o peso da folha de pagamento de especialistas no cálculo da CSLL. Distribuidoras de insumos agrícolas que transitam entre regimes acumulam crédito de ICMS nas entradas que, quando não escriturado mensalmente, vira ativo tributário represado sem gerar benefício de caixa.</p>
<p>A AC Contabilidade nasceu em 1996 e trinta anos acompanhando o setor sucroalcooleiro e a saúde especializada de Ribeirão Preto sedimentaram uma metodologia para identificar, com precisão, onde cada tipo de empresa acumula carga tributária além do necessário.</p>
<p>O levantamento tributário de entrada é gratuito e ocorre por reunião virtual. O escopo abrange regime vigente, créditos acumulados nos últimos sessenta meses e riscos identificados na escrituração atual.</p>"""

CORPUS["Sorocaba"] = """<p>Sorocaba estruturou seu parque produtivo ao longo da ferrovia que interliga Santos a Bauru, e hoje esse legado industrial se expressa em plantas de equipamentos elétricos de média e alta tensão, tecelagens técnicas, linhas de produção farmacêutica e fabricantes de autopeças que tornam a cidade a quarta maior economia do interior paulista. A diversidade de setores num mesmo perímetro urbano significa que obrigações fiscais com lógicas completamente distintas coexistem a poucos quarteirões de distância.</p>
<p>Fabricantes de equipamentos elétricos de alta tensão precisam classificar cada produto por TIPI para determinar se a saída é tributada, imune ou sujeita a alíquota reduzida de IPI: uma classificação incorreta gera estorno de crédito ou multa proporcional conforme o sentido do erro. Tecelagens técnicas que exportam tecidos especializados para o mercado têxtil global calculam o benefício de suspensão de tributos na aquisição de fios, mas o controle do saldo exportado por partida é o que determina se a suspensão se converte em isenção definitiva. Indústrias farmacêuticas instaladas no Distrito Industrial de Além Ponte operam com regimes de PIS e COFINS por alíquota diferenciada de produto, e qualquer divergência entre o regime declarado e o efetivamente praticado gera inconsistência que a Receita Federal detecta na cruzagem entre a EFD-Contribuições e a NFe.</p>
<p>A AC Contabilidade completou trinta anos acompanhando empresas da indústria de transformação e consolidou uma base de conhecimento setorial que permite detectar, com precisão, onde cada tipo de operação acumula carga tributária além do que a legislação exige.</p>
<p>Novos clientes de Sorocaba passam por uma triagem tributária gratuita conduzida à distância. A avaliação cobre o regime de tributação atual, o aproveitamento de crédito dos cinco exercícios anteriores e os pontos de atenção identificados nas declarações periódicas da empresa.</p>"""

CORPUS["Blumenau"] = """<p>Blumenau divide o espaço urbano entre o maior parque têxtil da Região Sul e um polo tecnológico com empresas de software, automação industrial e cibersegurança que faturaram mais de R$ 3 bilhões em 2023. A convivência entre teares jacquard e servidores de computação em nuvem não é apenas curiosidade histórica: ela cria obrigações fiscais com lógicas completamente distintas que convivem no mesmo perfil de contribuinte e exigem tratamento separado por atividade.</p>
<p>Fábricas de confecção do Vale do Itajaí que adotam o regime cumulativo de PIS e COFINS pagam alíquotas menores sobre a receita, mas abrem mão do crédito sobre insumos. Quando o volume de compras de tecido e aviamentos é alto em relação ao faturamento, o regime não cumulativo pode ser mais vantajoso, mas essa análise precisa ser feita com os números reais da empresa, não com estimativas setoriais. Marcas de moda blumenauenses que licenciam estampas e coleções para confeccionistas de outros estados precisam classificar o pagamento como royalty sujeito a IRPJ e CIDE ou como prestação de serviço sujeita a ISS, escolha que impacta diretamente a alíquota efetiva e a forma de retenção na fonte. Empresas de software com contratos de licença recorrente para clientes em municípios de outros estados enfrentam a controvérsia da LC 157/2016 sobre ISS: pagar no destino ou na origem é uma questão que cada prefeitura ainda interpreta à sua forma, gerando risco de bitributação ou de autuação por não retenção.</p>
<p>A AC Contabilidade consolidou desde 1996 uma metodologia para mapear o excedente tributário por atividade antes de propor qualquer ajuste de enquadramento, com trinta anos de prática com indústrias de transformação e prestadores de serviços.</p>
<p>Novos clientes de Blumenau recebem uma avaliação fiscal gratuita por videoconferência. O diagnóstico abrange o regime de tributação em vigor, os direitos creditórios dos últimos cinco exercícios e os pontos de inconsistência identificados na escrituração da empresa.</p>"""

if __name__ == "__main__":
    # Quando chamado diretamente, re-valida o corpus interno (deve ser tudo < 0.20 entre si)
    cities = list(CORPUS.keys())
    print("=== Validação cruzada do corpus ===")
    all_ok = True
    for i in range(len(cities)):
        for j in range(i+1, len(cities)):
            score = jaccard(CORPUS[cities[i]], CORPUS[cities[j]])
            status = "OK" if score < 0.20 else "FALHOU"
            if score >= 0.20:
                all_ok = False
            print(f"  {cities[i]:<20} vs {cities[j]:<20} {score:.3f}  {status}")
    print(f"\n  Corpus: {'consistente' if all_ok else 'INCONSISTENTE — revisar'}")
